### PR TITLE
Refresh e2fsprog patch and mark layer compatible with hardknott

### PR DESCRIPTION
**Pull request by clementperon**
Hi,

just a quick patch refresh for e2fsprog and mark the layer compatible with hardknott

### CODE REVIEW

**Review by kacf — APPROVED** [review]
Thanks!

**Comment by clementperon** [comment]
@kacf I think it was a mistake to mark these layer compatible with dunfell / hardknott.

If I understand correctly, now that new override syntax for Kirkstone / Honnister has been merged it's no more compatible with dunfell / hardknott. What do you think?

I can sent a patch to remove all dunfell / Hardknott compatibility

**Comment by TheYoctoJester** [comment]
@clementperon that is not completely necessary, `dunfell` gained backported syntax compatibility. `hardknott` should be removed, though.

**Comment by clementperon** [comment]
@TheYoctoJester, After searching for this I found :
```
The new syntax will work on the dunfell, gatesgarth, hardknott, master and new 
release branches going forward. That applies now and that support will be in the
next point releases for dunfell (3.1.11) and hardknott (3.3.3).
```

https://lists.yoctoproject.org/g/yocto/message/54368

**Comment by kacf** [comment]
Good!

Note that eventually all except kirkstone will be removed though, because we only support LTS branches in Mender. What we have now is temporary until we've released it.

**Comment by nandra** [comment]
@kacf  I'm using honister and this patch doesn't apply properly.

**Comment by clementperon** [comment]
@nandra sorry for that, are you talking about the e2fsprog ? 
I have indeed tested it on hardknott without checking honnister support.

I will check and resend to make it compatible with honnister.

**Comment by nandra** [comment]
@clementperon yes about this merge request. Thanks

**Comment by kacf** [comment]
> I'm using honister and this patch doesn't apply properly.

I have removed the patch in my latest local branch, I suspect it's not needed anymore. I'll push it soon, after I've cleaned it up.

**Comment by clementperon** [comment]
@kacf  found this thread trying to remove the patch https://github.com/mendersoftware/meta-mender/pull/1076

**Comment by kacf** [comment]
Very good find, @clementperon! I had forgotten about that. Looks like we need it then.

I'm currently based on what will become kirkstone (poky/master, currently at 3b8d67d4f0c05), so I'll refresh the patch relative to that.

**Comment by nandra** [comment]
@kacf when do you please expect to have this change merged? Thanks.

**Comment by kacf** [comment]
@nandra: You can already see it [here](https://github.com/mendersoftware/meta-mender/pull/1632) together with a lot of other fixes. I'm still having some problems compiling the client though (related to [this](https://github.com/mendersoftware/openssl/pull/37), which doesn't quite work yet), so it's still WIP.

**Pull request merged**
