### PR TITLE
mender: Setup rootfs partitions in automount blacklist.

### PR DESCRIPTION
**Pull request by drewmoseley**
Changelog: None
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by drewmoseley** [comment]
I thought about that but since the udev-extraconf recipe adds the /etc/udev/mount-blacklist.d directory it seems ok to add those files in from extra repos. And if udev-extraconf is not present, then it doesn't hurt anything.

**Comment by kacf** [comment]
Yes, I think it's fairly common for packages to add files to such {{.d}} directories, even if they are not used. That's at least how many deb packages do it.

**Comment by kacf** [comment]
Btw, @drewmoseley don't worry about the test error. It's a long standing issue that I'm finally going to fix now. Not related to your PR.

**Comment by kacf** [comment]
FYI: https://github.com/mendersoftware/meta-mender/pull/741

**Comment by kacf** [comment]
Rebased.

@mirzak: Ok with the `mount-blacklist.d` files, or do you still have concerns?

**Comment by mirzak** [comment]
> @mirzak: Ok with the mount-blacklist.d files, or do you still have concerns?

No concerns

**Pull request merged**
