### PR TITLE
rpi: Add workaround for display corruption in Warrior branch.

### PR DESCRIPTION
**Pull request by drewmoseley**
Changelog: title
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by mirzak** [comment]
Would it be more appropriate to put this patch in meta-raspberrypi (if U-Boot is enabled)? Nothing Mender specific here as I see it?

**Comment by drewmoseley** [comment]
I already submitted the kernel fix there.  This is just a workaround since we require u-boot.

**Comment by mirzak** [comment]
> I already submitted the kernel fix there. This is just a workaround since we require u-boot.

Yes, but would it not be useful for other users of meta-raspberrypi? You can enable U-Boot without Mender as well and hence why I am pushing to put it there.

**Comment by drewmoseley** [comment]
Once the kernel fix is accepted there this will not be needed.  I'm suggesting it here as a workaround since we control when the fix goes in here but not in meta-raspberrypi.

**Comment by mirzak** [comment]
I misunderstood, I though that both changes where needed. Then I do not have any further comments :)

**Comment by drewmoseley** [comment]
Thanks.  And sorry for not clarifying earlier.

**Comment by kacf** [comment]
Alright, merging then, since this is only for warrior, master is still prepared to use the upstream fix.

**Comment by drewmoseley** [comment]
Right.  In fact I just got the notification that my PR was merged.  I'll verify that it works and then revert this if possible.

**Pull request merged**
