### PR TITLE
fix: typo of mount option.

### PR DESCRIPTION
**Pull request by tunefs**
Fix mount option defaults being typo'd to default.

### CODE REVIEW

**Review by lluiscampos — CHANGES_REQUESTED** [review]
Hello @tunefs and thank you for your contribution. This is indeed wrong and I am surprised that it went unnoticed for so long :see_no_evil: 

The fix looks good. Two formalities missing:
* To comply with our licensing you need to sign your work. Read more here: https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#sign-your-work
* This is a good fix that we'll need to port to all our supported branches, so please mark it with a human readable changelog entry instead of `None`. For example "Fix typo in fstab options for extra partitions".

After that I can take care of running our test farm with your change :+1:

**Comment by tunefs** [comment]
Hello @lluiscampos 

Sorry for the delay.
I have added the 'Signed-off by' line and added a comment to the changelog.
Also rebased to the latest master.
Thank you very much.

**Review by lluiscampos — APPROVED** [review]

**Comment by lluiscampos** [comment]
> Hello @lluiscampos
> 
> Sorry for the delay. I have added the 'Signed-off by' line and added a comment to the changelog. Also rebased to the latest master. Thank you very much.

Fantastic, thank you.

To not bother you further, I amended the Python style to comply with the CI style check and force-pushed on your branch - I hope that that is okey with you.

I am running now this PR against our test farm and if nothing else pops up I will merge it.

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline

**Pull request merged**
