### PR TITLE
chore: Be more specific about what to install based on features.

### PR DESCRIPTION
**Pull request by kacf**

### CODE REVIEW

**Review by oleorhagen — COMMENTED** [review]
Thanks! There are a few others left also. 

Can you have a look through all the other `mender_%.bbappend` files? :pray:

**Comment by oleorhagen** [comment]
> > Thanks! There are a few others left also.
> > Can you have a look through all the other `mender_%.bbappend` files? 🙏
> 
> I couldn't find anything. Is there anything specific you spotted?

Yes, I'm pretty sure we have some `.inc` files with `:${PN}` suffixes in there, which will not work, right? :thinking: 

Like here:

```
RDEPENDS:${PN}:append:mender-image:qemuall = " softhsm opensc gnutls p11-kit libp11 gnutls-bin"
```

**Review by lluiscampos — APPROVED** [review]
From my side it looks good.

**Comment by kacf** [comment]
> > > Thanks! There are a few others left also.
> > > Can you have a look through all the other `mender_%.bbappend` files? 🙏
> > 
> > 
> > I couldn't find anything. Is there anything specific you spotted?
> 
> Yes, I'm pretty sure we have some `.inc` files with `:${PN}` suffixes in there, which will not work, right? 🤔
> 
> Like here:
> 
> ```
> RDEPENDS:${PN}:append:mender-image:qemuall = " softhsm opensc gnutls p11-kit libp11 gnutls-bin"
> ```

Ah you're right, I didn't think about `${PN}`. It's independent though, so I'll follow up on that separately.

The failures are just known failures which have since been fixed (filetransfer tests broke this week), so merging.

**Pull request merged**
