### PR TITLE
Remove Go compilation tweaks not needed anymore with latest Go layer.

### PR DESCRIPTION
**Pull request by kacf**
Signed-off-by: Kristian Amlie <kristian.amlie@mender.io>

### CODE REVIEW

**Comment by kacf** [comment]
@GregorioDiStefano: Try this.

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by kacf** [comment]
Superseded by #84.

**Pull request closed without merging**
