### PR TITLE
fix: persistent machine id support files renamed

### PR DESCRIPTION
**Pull request by TheYoctoJester**
The script to write a persistent systemd machine id
along with the correlating systemd service unit have
been renamed. Adjust the filenames in mender-client-cpp.inc
accordingly.

Changelog: Title
Ticket: None

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Review by lluiscampos — CHANGES_REQUESTED** [review]
The files were [renamed](https://github.com/mendersoftware/meta-mender/commit/98341dd128d3cc51d9650c1fdb44232bebf140fd):

```
$ find . -name *systemd-machine-id*
./meta-mender-core/recipes-mender/mender-client/files/mender-set-systemd-machine-id.sh
./meta-mender-core/recipes-mender/mender-client/files/mender-systemd-machine-id.service
```

I think we need to fix the recipe instead:
```
$ git diff
diff --git a/meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc b/meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc
index 54232593..68d5f11e 100644
--- a/meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc
+++ b/meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc
@@ -90,8 +90,8 @@ SRC_URI:append:mender-image:mender-systemd = " \
 "
 
 SRC_URI:append:mender-persist-systemd-machine-id = " \
-    file://mender-client-systemd-machine-id.service \
-    file://mender-client-set-systemd-machine-id.sh \
+    file://mender-systemd-machine-id.service \
+    file://mender-set-systemd-machine-id.sh \
 "
 
 SRC_URI:append:mender-growfs-data:mender-systemd = " \
```

**Review by lluiscampos — APPROVED** [review]

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline

**Comment by TheYoctoJester** [comment]
@lluiscampos please note, I just adjusted the PR description and comment.

**Comment by TheYoctoJester** [comment]
@mender-test-bot cherry-pick to:
- scarthgap

**Comment by lluiscampos** [comment]
@TheYoctoJester Only now I realized that I broke this myself by wrongly cherry-picking a fix from kirkstone to master. See https://github.com/mendersoftware/meta-mender/pull/2146 :see_no_evil:

**Comment by skinny** [comment]
The `mender-client-cpp.inc` file contains some more references to  `mender-client-*` instead of `mender-*` which breaks my test build when upgrading to the `scarthgap` branch.

```diff --git a/meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc b/meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc
index 68d5f11e..426de224 100644
--- a/meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc
+++ b/meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc
@@ -114,9 +114,9 @@ FILES:mender-update:append:mender-growfs-data:mender-systemd = " \
 "

 FILES:mender-update:append:mender-persist-systemd-machine-id = " \
-    ${systemd_unitdir}/system/mender-client-systemd-machine-id.service \
-    ${systemd_unitdir}/system/${MENDER_CLIENT}.service.wants/mender-client-systemd-machine-id.service \
-    ${bindir}/mender-client-set-systemd-machine-id.sh \
+    ${systemd_unitdir}/system/mender-systemd-machine-id.service \
+    ${systemd_unitdir}/system/${MENDER_CLIENT}.service.wants/mender-systemd-machine-id.service \
+    ${bindir}/mender-set-systemd-machine-id.sh \
 "

 FILES:mender-config += "\
@@ -326,11 +326,11 @@ do_install:append:class-target:mender-growfs-data:mender-systemd() {
 }

 do_install:append:class-target:mender-persist-systemd-machine-id() {
-    install -m 644 ${WORKDIR}/mender-client-systemd-machine-id.service ${D}${systemd_unitdir}/system/
+    install -m 644 ${WORKDIR}/mender-systemd-machine-id.service ${D}${systemd_unitdir}/system/
     install -d -m 755 ${D}${systemd_unitdir}/system/${MENDER_CLIENT}.service.wants
-    ln -sf ../mender-client-systemd-machine-id.service ${D}${systemd_unitdir}/system/${MENDER_CLIENT}.service.wants/
+    ln -sf ../mender-systemd-machine-id.service ${D}${systemd_unitdir}/system/${MENDER_CLIENT}.service.wants/
     install -d -m 755 ${D}${bindir}
-    install -m 755 ${WORKDIR}/mender-client-set-systemd-machine-id.sh ${D}${bindir}/
+    install -m 755 ${WORKDIR}/mender-set-systemd-machine-id.sh ${D}${bindir}/
 }

 do_install() {```

**Comment by lluiscampos** [comment]
> The `mender-client-cpp.inc` file contains some more references to `mender-client-*` instead of `mender-*` which breaks my test build when upgrading to the `scarthgap` branch.
> (...)

Yes. Sorry for that. There is a work in progress fix here:
* https://github.com/mendersoftware/meta-mender/pull/2158

**Comment by skinny** [comment]
> > The `mender-client-cpp.inc` file contains some more references to `mender-client-*` instead of `mender-*` which breaks my test build when upgrading to the `scarthgap` branch.
> > (...)
> 
> Yes. Sorry for that. There is a work in progress fix here:
> 
> * [[scarthgap] chase persistent machine id renames #2158](https://github.com/mendersoftware/meta-mender/pull/2158)

And sorry I missed that, thanks!

**Pull request merged**
