### PR TITLE
[dunfell] Add recipe for 2.5.0 release

### PR DESCRIPTION
**Pull request by lluiscampos**
Changelog: Add mender-client 2.4.0 recipe.

### CODE REVIEW

**Comment by lluiscampos** [comment]
Building together with 2.5.0 release @ [Pipeline 188720303](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/188720303)

**Review by kacf — APPROVED** [review]

**Comment by lluiscampos** [comment]
> Building together with 2.5.0 release @ [Pipeline 188720303](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/188720303)

Retrying @ [Pipeline 188834503](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/188834503)

**Comment by lluiscampos** [comment]
> > Building together with 2.5.0 release @ [Pipeline 188720303](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/188720303)
> 
> Retrying @ [Pipeline 188834503](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/188834503)

New build @ [Pipeline 189089612](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/189089612)

**Comment by lluiscampos** [comment]
> > > Building together with 2.5.0 release @ [Pipeline 188720303](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/188720303)
> > 
> > 
> > Retrying @ [Pipeline 188834503](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/188834503)
> 
> New build @ [Pipeline 189089612](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/189089612)

Turns out that `dunfell` is behind quite behing `master` ATM so that we cannot  build the release here. Namely: we are missing the HSM module in QEMU for the integratoin test. Building the release in #1087 instead...

**Comment by kacf** [comment]
> Turns out that `dunfell` is behind quite behing `master` ATM so that we cannot build the release here. Namely: we are missing the HSM module in QEMU for the integratoin test. Building the release in #1087 instead...

Yes, I also noticed this in #1086. I'm working on fixing it.

**Pull request merged**
