### PR TITLE
New Mender binary delta releases

### PR DESCRIPTION
**Pull request by kacf**

### CODE REVIEW

**Comment by kacf** [comment]
Wait a minute. I should remove all of the recipes that are incompatible with libubootenv, both here and on dunfell.

**Comment by kacf** [comment]
There, fixed!

**Review by lluiscampos — APPROVED** [review]
I also looked at the pushed tags, the pipelines and the S3 buckets contents. All looks good :+1:

**Comment by kacf** [comment]
Thanks!

**Pull request merged**
