### PR TITLE
dunfell: Simplify mender-client-resize-data-part and make it compatible with "partuuid" setups

### PR DESCRIPTION
**Pull request by ColinFinck**
Backport of #1685 to the dunfell branch.

### CODE REVIEW

**Review by kacf — CHANGES_REQUESTED** [review]
Hey @ColinFinck, can you please use `git cherry-pick -x <SHA>` when backporting. They should be the same as the originals, just with the extra cherry-pick string added.

**Comment by ColinFinck** [comment]
@kacf While dunfell suffers from the same mender-client-resize-data-part bug in a "partuuid" setup, it does not support the "partlabel" feature.
This is why an exact cherry-pick of the two commits from master with no code changes is not possible.

Shall I split this up into the original two commits with added cherry-pick string anyway, and just hide the necessary changes for dunfell in the diffs?
Or do you propose another method to make it clear that this is not an exact copy of the commits to master?

**Comment by kacf** [comment]
I think the first method is preferred, as long as the patch at least resembles the original. If it's completely different then one can reevaluate, but solving conflicts and getting a slightly different patch is quite common during backporting. It's still useful that they look similar for tracking purposes.

**Comment by ColinFinck** [comment]
@kacf Ok, cherry-picked both commits as suggested. Should be ready for review now.

**Review by kacf — APPROVED** [review]

**Comment by kacf** [comment]
Retrying this pipeline in #1727.

**Comment by kacf** [comment]
Retrying this pipeline in #1727.

**Pull request closed without merging**
