### PR TITLE
scarthgap: updates for release v2024.12

### PR DESCRIPTION
**Pull request by lluiscampos**
Bringing from `master` everything that has not been yet ported since last release.

### CODE REVIEW

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline

**Comment by lluiscampos** [comment]
Build for Mender 3.7.8 @ [Pipeline 1573941803](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/1573941803)

**Review by danielskinstad — APPROVED** [review]

**Comment by lluiscampos** [comment]
Repeating the builds with `scarthgap-next`:
* Mender master @ [Pipeline 1576422348](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/1576422348)
* Mender 3.7.8 @ [Pipeline 1576422957](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/1576422957)

**Comment by TheYoctoJester** [comment]
Gave it a read, but I don't feel competent to judge on the go compilation changes. The rest looks fine to me, so I trust @danielskinstad reviewing.

**Pull request merged**
