### PR TITLE
test: Update test_preferred_versions to new separator syntax

### PR DESCRIPTION
**Pull request by lluiscampos**
I wanted only to submit this dummy but annoying fix:

    chore: Update commented out build conf settings with new separator

And ended up finding this one:

    test: Update test_preferred_versions to new separator syntax
    
    By the looks of it, EXTERNALSRC_ and PREFERRED_VERSION_ did not trigger
    warnings or errors and this mistake went unnoticed. The test "passes"
    because it just builds always the latest available recipe.

### CODE REVIEW

**Review by kacf — APPROVED** [review]
Ouch. Good catch!

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline

**Review by oleorhagen — APPROVED** [review]

**Comment by lluiscampos** [comment]
New commit

    fix: Add missing licenses checksums for bugfix recipes
    
    Changelog: Add missing licenses checksums for mender-client 3.3.1 recipe
    Changelog: Add missing licenses checksums for mender-artifact 3.8.1 recipe

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline again :repeat:

**Review by kacf — APPROVED** [review]

**Comment by lluiscampos** [comment]
> New commit
> 
> ```
> fix: Add missing licenses checksums for bugfix recipes
> 
> Changelog: Add missing licenses checksums for mender-client 3.3.1 recipe
> Changelog: Add missing licenses checksums for mender-artifact 3.8.1 recipe
> ```

I extended further the fixes:

    Changelog: Add missing licenses checksums, set right preference, and
    correct dependencies syntax for mender-client 3.3.1 recipe
    Changelog: Add missing licenses checksums, set right preference, and
    add missing license for mender-artifact 3.8.1 recipe

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline one more time :microphone:

**Comment by lluiscampos** [comment]
@mender-test-bot cherry-pick to:
* kirkstone

**Pull request merged**
