### PR TITLE
u-boot: Switch Raspberry Pi to store env on MMC, after 2a8ea346aa0d.

### PR DESCRIPTION
**Pull request by kacf**
Signed-off-by: Kristian Amlie <kristian.amlie@mender.io>

### CODE REVIEW

**Comment by kacf** [comment]
@mirzak: I believe the Raspberry Pi will need a patch like this after the latest changes. Can you take a look?

**Comment by mirzak** [comment]
Cool. I will look in to this.

**Comment by mirzak** [comment]
Created a pull request #201

**Comment by kacf** [comment]
Absolutely, yours is more complete.

**Pull request closed without merging**
