### PR TITLE
backport U-boot redundant U-boot environment to morty

### PR DESCRIPTION
**Pull request by mirzak**
I missed that you had pulled raspberrypi support to morty, the u-boot
patches did not apply since morty runs on 2016.03 and master is 2017.01.

### CODE REVIEW

**Comment by mirzak** [comment]
Silly me playing around with `hub`, will re-create

**Comment by mirzak** [comment]
Closing this

**Comment by kacf** [comment]
Yes, morty pulls directly from master, with a couple of additional patches to revert to older patches/methods/etc.

**Comment by mirzak** [comment]
I created #236 instead which targets morty, my mistake was that this one accidentally targeted "master". I later realized that you can actually edit a pull-request to change target branch. But I realized that first when I created the second

**Pull request closed without merging**
