### PR TITLE
Boot fs type

### PR DESCRIPTION
**Pull request by drewmoseley**
# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits have a [`Changelog`](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Respect the boot fstype specifiers when generating the partitions.

### CODE REVIEW

**Comment by drewmoseley** [comment]
I just found this.  Hopefully that is the cause if this test failure:
```
diff --git a/meta-mender-core/classes/mender-ubimg.bbclass b/meta-mender-core/classes/mender-ubimg.bbclass
index 41f7c401..9ebba740 100644
--- a/meta-mender-core/classes/mender-ubimg.bbclass
+++ b/meta-mender-core/classes/mender-ubimg.bbclass
@@ -110,7 +110,7 @@ EOF
 
 }
 
-IMAGE_TYPEDEP_ubimg_append = " ubifs dataimg ${@bb.utils.contains('MENDER_BOOT_PART_SIZE_MB', '0', '', 'bootimg', d)}"
+IMAGE_TYPEDEP_ubimg_append = " ubifs dataimg $@{bb.utils.contains('MENDER_BOOT_PART_SIZE_MB', '0', '', 'bootimg', d)}"

```

**Comment by drewmoseley** [comment]
And this typo:
```
diff --git a/meta-mender-core/classes/mender-part-images.bbclass b/meta-mender-core/classes/mender-part-images.bbclass
index 1ef26ffe..69664ffa 100644
--- a/meta-mender-core/classes/mender-part-images.bbclass
+++ b/meta-mender-core/classes/mender-part-images.bbclass
@@ -325,7 +325,7 @@ python() {
 python() {
     if d.getVar('MENDER_BOOT_PART_SIZE_MB', True) != "0":
         d.appendVar('IMAGE_TYPEDEP_sdimg', ' bootimg')
-        d.appendVar('IMAGE_TYPEDEP_uefiimg', ' bootimg')
+        d.appendVar('IMAGE_TYPEDEP_uefimg', ' bootimg')
         d.appendVar('IMAGE_TYPEDEP_biosimg', ' bootimg')
         d.appendVar('IMAGE_TYPEDEP_gptimg', ' bootimg')
 }
```

**Comment by drewmoseley** [comment]
ok.  this passes now but I am not sure it's correct.  Please don't merge yet.

**Comment by lluiscampos** [comment]
@drewmoseley Just merge it yourself whenever you are confident. I will not touch it.

**Pull request merged**
