### PR TITLE
toradex-nxp: Fix build failures with new U-Boot autoconfiguration.

### PR DESCRIPTION
**Pull request by drewmoseley**
Changelog: None

### CODE REVIEW

**Comment by drewmoseley** [comment]
@kacf do you know of any better way to fix this?  I'm getting parse errors when building the Toradex config.

**Comment by kacf** [comment]
Hmm, a parse error you say? That's a bit mysterious. Can you post what it is?

And independently from that, could you try to remove both of the `PREFERRED_PROVIDER_u-boot-fw-utils`, `PREFERRED_RPROVIDER_u-boot-fw-utils` (keep the `bbappend` file if you need to)? The new auto patcher is supposed to pick up that you don't have any provider of u-boot-fw-utils and should provide its own, based on the sources of u-boot itself.

**Comment by drewmoseley** [comment]
Without this change I get the following:
```
ERROR: Task do_save_mender_auto_configured_patch in /work/dmoseley/Mender/yocto/master/src/poky/meta/recipes-bsp/u-boot/u-boot-fw-utils_2017.11.bb depends upon non-existent task do_mender_uboot_auto_configure in /work/dmoseley/Mender/yocto/master/src/meta-toradex-nxp/recipes-bsp/u-boot/u-boot-toradex-fsl-fw-utils_git.bb
ERROR: Command execution failed: 1
```

**Comment by kacf** [comment]
Thanks Drew! Both of these are really nice finds, and should be fixed at the root. The second issue is easy to fix, the first is a bit trickier, but I will try. Ideally the only change you should need to make is the removal of the `PREFERRED_PROVIDERs`. To be continued.

**Comment by kacf** [comment]
I think I found the root cause of both issues. Can you try rebasing your branch on top of #454? It would be nice if you could verify both of the issues you had, because both are valid use cases.

* One where `PREFERRED_PROVIDER_u-boot-fw-utils` is removed
* One where `PREFERRED_RPROVIDER_u-boot-fw-utils` is added
* In both cases `MENDER_UBOOT_AUTO_CONFIGURE = "0"` should be removed

Although both are valid, I think that ultimately the top method is the proper fix that should be submitted for toradex.

**Comment by drewmoseley** [comment]
@kacf, with the removal of the extra u-boot-fw-utils_%.bbappend, and merging in your branch from #454, it builds fine when I set both PREFERRED_* variables.

When I remove them both I get:
```
ERROR: u-boot-fw-utils-mender-auto-provided-1.0-r0 do_package: objcopy failed with exit code 1 (cmd was 'arm-poky-linux-gnueabi-objcopy' --only-keep-debug '/work/dmoseley/Mender/yocto/master/build/│····
colibri-imx7-mender/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/u-boot-fw-utils-mender-auto-provided/1.0-r0/package/sbin/fw_setenv' '/work/dmoseley/Mender/yocto/master/build/colibri-imx7-mender/tmp│····
/work/cortexa7hf-neon-poky-linux-gnueabi/u-boot-fw-utils-mender-auto-provided/1.0-r0/package/sbin/.debug/fw_setenv'):                                                                                │····
arm-poky-linux-gnueabi-objcopy:/work/dmoseley/Mender/yocto/master/build/colibri-imx7-mender/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/u-boot-fw-utils-mender-auto-provided/1.0-r0/package/sbin/fw_s│····
etenv: File format not recognized                                                                                                                                                                    │····
ERROR: u-boot-fw-utils-mender-auto-provided-1.0-r0 do_package: Function failed: split_and_strip_files                                                                                                │····
ERROR: Logfile of failure stored in: /work/dmoseley/Mender/yocto/master/build/colibri-imx7-mender/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/u-boot-fw-utils-mender-auto-provided/1.0-r0/temp/log.do│····
_package.830                                                                                                                                                                                         │····
ERROR: Task (/work/dmoseley/Mender/yocto/master/src/meta-mender/meta-mender-core/recipes-bsp/u-boot/u-boot-fw-utils-mender-auto-provided_1.0.bb:do_package) failed with exit code '1'                
```

**Comment by kacf** [comment]
I think the only way I can solve that is by building this myself. What layers are you using to build for toradex? Any special `local.conf` settings?

I think this is quite important to fix, since it is one of the main automation steps.

**Comment by drewmoseley** [comment]
@kacf specifically I use the following:

- https://github.com/drewmoseley/poky/tree/wip-master
- https://github.com/Freescale/meta-freescale/commit/0f69a2a87cb066c3303197f22d7579840612c557
- https://github.com/drewmoseley/meta-freescale-3rdparty/tree/wip-master
- https://github.com/drewmoseley/meta-toradex-bsp-common/tree/wip-master
- https://github.com/drewmoseley/meta-toradex-nxp/tree/wip-master

As well as meta-mender, meta-mender-demo and meta-mender-toradex-nxp on the master branch

**Comment by kacf** [comment]
Thank you! I'll give that a spin.

**Comment by kacf** [comment]
After investigating the issue I have found that it is a bug in U-Boot versions before v2017.05. While it would be possible to work around it, the fix is quite complicated. I don't think it will affect future versions, so I think I will save the effort, and leave this unfixed.

This means that you can revert to the method of defining both the providers, and this is also what we should recommend if other people hit this on the list, at least if their U-Boot stems from a pre-v2017.05 release. I will add the specific message you got to the troubleshooting guide.

**Comment by drewmoseley** [comment]
@kacf do I need any changes other than the PREFERRED_VERSION variables?  What about #454?

**Comment by kacf** [comment]
@drewmoseley: Can you check that https://github.com/mendersoftware/mender-docs/pull/351 is written ok?

**Comment by kacf** [comment]
> do I need any changes other than the PREFERRED_VERSION variables? What about #454?

Yes, you also need that one. Best if you just rebase on top of it and test it all together in this PR.

**Comment by kacf** [comment]
Superseded by https://github.com/kacf/meta-mender/pull/1.

**Pull request closed without merging**
