### PR TITLE
Work around error from QEMU: "Failed to lock byte 100"

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by kacf** [comment]
Welcome to Mender world! You need to both add a "Signed-off-by" tag and a "Changelog: title" tag to your commit!

**Comment by jimis** [comment]
Thank you for the warm welcome, dear @kacf. I have signed off my significant contribution.

**Comment by mirzak** [comment]
Welcome @jimis :)

**Comment by jimis** [comment]
:-)

**Pull request merged**
