### PR TITLE
Group u-boot patch files into boards.

### PR DESCRIPTION
**Pull request by kacf**
Much easier to see which patches belong where.

Signed-off-by: Kristian Amlie <kristian.amlie@mender.io>

### CODE REVIEW

**Comment by kacf** [comment]
@bboozzoo

**Comment by bboozzoo** [comment]
I'm leaning towards NACK. I suppose now could be the right time to introduce BSP/device layers. Uboot would fit there perfecly.

**Comment by kacf** [comment]
Would this be a separate layer, `meta-mender-bsp`?

**Comment by kacf** [comment]
I think you're right. It's more work, but it's better long term.

**Pull request closed without merging**
