### PR TITLE
fix: Make sure the mender-image-full-cmdline-rofs-commercial builds

### PR DESCRIPTION
**Pull request by oleorhagen**
Previously, the commercial layer had an implicit dependency on the demo layer,
due to the inclusion of the `mender-image-full-cmdline-rofs` image recipe.

The fix is simply to share this through moving the recipe to mender-core.

Ticket: None
Changelog: None

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Comment by oleorhagen** [comment]
I moved it to `mender-core` to not have any dependencies on commercial for this one. but feel free to correct me here.

**Review by kacf — APPROVED** [review]

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by zach-welch-aquabyte** [comment]
This issue presently blocks me from spinning previews of our images for the kirkstone-4.0.7 release using the latest mender branch. I have worked around it by rolling back to the commit before this recipe was added, but it would be nice to see this get merged soon.

**Comment by oleorhagen** [comment]
@mender-test-bot cherry-pick to: `kirkstone`, `dunfell`

**Pull request merged**
