### PR TITLE
warrior update v2021.04

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
Builds:
* Mender 2.7.0 @ [Pipeline 289138305](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/289138305)
* Mender 2.6.1 @ [Pipeline 289138464](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/289138464)
* Mender 2.4.3 @ [Pipeline 289138678](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/289138678)

**Comment by lluiscampos** [comment]
New builds:
* Mender 2.7.0 @ [Pipeline 289341039](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/289341039)
* Mender 2.6.1 @ [Pipeline 289341273](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/289341273)
* Mender 2.4.3 @ [Pipeline 289337235](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/289337235)

**Comment by lluiscampos** [comment]
Mender 2.4.3 build passed in previous run. Last commit is only relevant for Mender 2.6 and newer. New builds:
* Mender 2.7.0 @ [Pipeline 289932906](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/289932906)
* Mender 2.6.1 @ [Pipeline 289933038](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/289933038)

**Comment by lluiscampos** [comment]
Missing changelog tag :sob:. New builds:
* Mender 2.7.0 @ [Pipeline 290022076](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/290022076)
* Mender 2.6.1 @ [Pipeline 290022244](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/290022244)

**Review by kacf — APPROVED** [review]

**Comment by lluiscampos** [comment]
The `test_state_scripts` failures are addressed in https://github.com/mendersoftware/integration/pull/1329

Repeating (integration tests only) build for Mender 2.7.0 together with the mentioned PR @ [Pipeline 290626935](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/290626935)

**Pull request merged**
