### PR TITLE
Add panic option to bootloader boot arguments.

### PR DESCRIPTION
**Pull request by pasinskim**
Having panic option set as a part of boot arguments we will be able
to restart boot process once booting kernel will hang.

### CODE REVIEW

**Comment by kacf** [comment]
Looks good to me.

**Comment by GregorioDiStefano** [comment]
what ever happened to this PR?

**Comment by kacf** [comment]
I guess I expected @pasinskim to merge it. Can you rebase it, @pasinskim? It's out of date now.

**Comment by pasinskim** [comment]
@kacf done. If you are good with this one I can merge it.

**Comment by kacf** [comment]
Yep, go ahead!

**Pull request merged**
