### PR TITLE
Pyro backports

### PR DESCRIPTION
**Pull request by drewmoseley**

### CODE REVIEW

**Comment by kacf** [comment]
See also [the morty backports](https://github.com/mendersoftware/meta-mender/pull/611#issuecomment-423452711).

**Comment by drewmoseley** [comment]
@kacf now I'm getting

> 16:51:08 + pytest_args=--no-pull
> 16:51:08 + local qemu_testing_status=0
> 16:51:08 + py.test -p no:xdist --verbose --junit-xml=results.xml --bitbake-image core-image-minimal --board-type=vexpress-qemu-flash --no-pull --html=report.html --self-contained-html
> 16:51:08 usage: py.test [options] [file_or_dir] [file_or_dir] [...]
> 16:51:08 py.test: error: unrecognized arguments: --no-pull

**Comment by drewmoseley** [comment]
I think https://github.com/mendersoftware/mender-qa/pull/218 will fix the "--no-pull" issue.  Not sure about the s3cmd although I feel like I've seen that before.

**Comment by drewmoseley** [comment]
I also added a commit to that same PR to at least work around the s3cmd failure.

**Comment by drewmoseley** [comment]
@kacf it looks like this is the same "missing scp" issue.

**Comment by drewmoseley** [comment]
Yay.  All green except for qemux86-64 which does not exist on this branch.  Merging.

**Pull request merged**
