### PR TITLE
Pyro

### PR DESCRIPTION
**Pull request by drewmoseley**
@kacf anything here you think we should drop from Pyro?

### CODE REVIEW

**Comment by drewmoseley** [comment]
That's a bit odd of a build failure:
```
15:23:59 Applying patch 0002-Integration-of-Mender-boot-code-into-U-Boot.patch
15:23:59 patching file include/env_default.h
15:23:59 patching file scripts/Makefile.autoconf
15:23:59 Hunk #1 FAILED at 98.
15:23:59 1 out of 1 hunk FAILED -- rejects in file scripts/Makefile.autoconf
15:23:59 Patch 0002-Integration-of-Mender-boot-code-into-U-Boot.patch does not apply (enforce with -f)
15:23:59 ERROR: u-boot-1_2017.05-r0 do_patch: Function failed: patch_do_patch
15:23:59 ERROR: Logfile of failure stored in: /home/jenkins/workspace/yoctobuild/build-qemu/tmp/work/vexpress_qemu-poky-linux-gnueabi/u-boot/1_2017.05-r0/temp/log.do_patch.5195
15:23:59 NOTE: recipe u-boot-1_2017.05-r0: task do_patch: Failed
15:23:59 ERROR: Task (/home/jenkins/workspace/yoctobuild/meta/recipes-bsp/u-boot/u-boot_2017.05.bb:do_patch) failed with exit code '1'
15:23:59 NOTE: recipe mender-1.2.0b1-r0: task do_compile: Succeeded
15:23:59 NOTE: recipe u-boot-fw-utils-1_2017.05-r0: task do_unpack: Succeeded
15:24:00 NOTE: Tasks Summary: Attempted 3919 tasks of which 3081 didn't need to be rerun and 1 failed.
15:24:00 
```
Not sure how my patches could cause that.  I'll try a local build.

**Comment by kacf** [comment]
Never mind about the failure. The tester isn't yet smart enough to understand that it needs to build the pyro branch from poky together with pull requests that target the meta-mender/pyro branch. I have [run the job manually](https://mender-jenkins.mender.io/job/mender-builder/1975).

**Comment by kacf** [comment]
Retried [here](https://mender-jenkins.mender.io/job/mender-builder/1992/).

**Comment by kacf** [comment]
The last error is irrelevant, it was my mistake for passing the wrong arguments to Jenkins. Merging this!

**Pull request merged**
