### PR TITLE
Restore running checksum test and revert root filesystem labels

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
This PR brings https://github.com/mendersoftware/mender-image-tests/pull/32, which will make run again `test_equal_checksum_part_image_and_artifact`.

I'll let it run the full pipeline to confirm my deduction that this test is failing in master.

**Comment by lluiscampos** [comment]
As expected, this test failed for all applicable configurations, see [pipeline 228157234](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/228157234).

Pushed now the revert of the original fix and rerunning the pipeline.

**Review by kacf — APPROVED** [review]
When you merge this, can you also post a comment [here](https://github.com/mendersoftware/meta-mender/pull/1162)?

**Review by oleorhagen — APPROVED** [review]
`s/fromt he/from the/`

**Comment by oleorhagen** [comment]
And good find :+1:

**Comment by lluiscampos** [comment]
Last force-push consists of updating the submodule after merge and a typo fix in the commit message.

The last build with all acceptance tests passing can be found at [Pipeline 228308422](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/228308422).

**Comment by lluiscampos** [comment]
@kacf I will port this soon to `zeus`, as I still have a pending release there. I leave in your hands the port to `dunfell`.

**Comment by kacf** [comment]
> I will port this soon to `zeus`, as I still have a pending release there. I leave in your hands the port to `dunfell`.

Ack. I will probably wait for the Mender release for the next dunfell tag. Because you cannot delta-update straight from a uefiimg anyway, this is just future proofing.

**Pull request merged**
