### PR TITLE
Rocko backports

### PR DESCRIPTION
**Pull request by drewmoseley**

### CODE REVIEW

**Comment by drewmoseley** [comment]
@kacf just trying to keep up with your monthly tags.  Anything obviously wrong here?

**Comment by nandra** [comment]
Sorry for bothering just want to ask when it is expected to have this merged. Thanks.

**Comment by drewmoseley** [comment]
@nandra hopefully tonight or tomorrow morning.

**Comment by drewmoseley** [comment]
@kacf can qemux86-64-uefi-grub_integration_master be ignored for Rocko?

**Comment by kacf** [comment]
Not in general, but that failure is a known spurious one (some race condition between the microservices, the server guys know about it). From my POV this can be merged.

**Pull request merged**
