### PR TITLE
fix(test): Do not decode log file as UTF-8

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Review by merlin-northern — APPROVED** [review]
wow, you are my hero

**Review by kacf — APPROVED** [review]
Nice fix! I already fixed this in kirkstone in a different way, but your fix is better. I will steal it! 🙂

**Comment by tranchitella** [comment]
Duplicate of https://github.com/mendersoftware/meta-mender/pull/1743, let's coordinate when merging.

**Comment by tranchitella** [comment]
Superseded by the other PR.

**Pull request closed without merging**
