### PR TITLE
Raspberry Pi 5 Mender Support for Yocto Release Scarthgap

### PR DESCRIPTION
**Pull request by leon-anavi**
# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Comment by TheYoctoJester** [comment]
Hi @leon-anavi,

Thanks a lot for assembling this. Unfortunately, the current plan is to keep the RPi5 in community state, e.g. we will not be support for it in meta-mender at the current point in time. Can you maybe rework the patchset into a meta-mender-communty/meta-mender-raspberrypi-community layer? Just like we already have for qemu.

Thanks!

**Comment by leon-anavi** [comment]
Hi @TheYoctoJester,

> Thanks a lot for assembling this. Unfortunately, the current plan is to keep the RPi5 in community state, e.g. we will not be support for it in meta-mender at the current point in time. Can you maybe rework the patchset into a meta-mender-communty/meta-mender-raspberrypi-community layer? Just like we already have for qemu.

OK, next week I will rework this GitHub pull request for meta-mender-communty/meta-mender-raspberrypi-community. Is this approach with additional layer [meta-lts-mixins](https://git.yoctoproject.org/meta-lts-mixins) for U-Boot 2024.04 acceptable for you?

Best regards, Leon

**Comment by TheYoctoJester** [comment]
Hi @leon-anavi,perfect! No need to hurry. I need to figure out `scarthgap`anyways ;-)

**Comment by leon-anavi** [comment]
Hi @TheYoctoJester,

Could you please create branch scarthgap (or master-next) in git repository [meta-mender-community](https://github.com/mendersoftware/meta-mender-community) ? I will need it for the rpi5 work.

Best regards,
Leon

**Comment by leon-anavi** [comment]
Hi @TheYoctoJester,

I split and reworked the commits from this GitHub pull request. I opened a new GitHub pull request that just adds Scarthgap support to meta-mender-core and meta-mender-raspberrypi (but no Raspberry Pi 5 though): https://github.com/mendersoftware/meta-mender/pull/2103

Could you please create branch scarthgap (or master-next) in git repository [meta-mender-community](https://github.com/mendersoftware/meta-mender-community) ? I will need to open a GitHub pull request an add a patches to enable Mender on Raspberry Pi 5.

Thanks,
Leon

**Pull request closed without merging**
