### PR TITLE
Changelog:All: Bump alpine in /meta-mender-qemu/docker/qemux86-64

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
@kacf The extra functionality that we introduced in `setup-mender-configuration.py` require Python 3.9 or newer. The simplest is just updating the base image here - do you have objections?

Error trace follows:
```
Traceback (most recent call last):
  File "./setup-mender-configuration.py", line 138, in <module>
    main()
  File "./setup-mender-configuration.py", line 87, in main
    server_host = args.server_url.removeprefix("http://").removeprefix("https://")
AttributeError: 'str' object has no attribute 'removeprefix'
```

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline

**Comment by kacf** [comment]
> The simplest is just updating the base image here - do you have objections?

I think that's fine. But maybe update the `vexpress-qemu` Dockerfile too? Even if we don't end up using that particular feature with it, I think it's better if they are in sync. And it's getting quite outdated.

**Review by kacf — APPROVED** [review]
> @kacf We [have removed `vexpress-qemu/Dockerfile` from master](https://github.com/mendersoftware/meta-mender/commit/169d615258c22951219638c05fabbea747c231a4), so there is nothing I can cherry-pick from there. I could update it manually but have no capacity to test it today, so I will let it be as is. Sorry.

No, you're right, I was mixing this with the vexpress-qemu acceptance testing, but it doesn't use the Dockerfile. All looks good!

**Comment by lluiscampos** [comment]
The following [integration tests](https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/2279695498) failed:
```
FAILED tests/test_mender_connect.py::TestRemoteTerminal::test_bogus_proto_message
FAILED tests/test_mender_connect.py::TestRemoteTerminal_1_0::test_regular_protocol_commands
FAILED tests/test_mender_connect.py::TestRemoteTerminal_1_0::test_session_recording
FAILED tests/test_os_ent_migration.py::TestEntMigration::test_devs_ok - asser...
FAILED tests/test_mender_gateway.py::TestMenderGatewayOpenSource::test_deployment_gateway_and_one_device
```

Although suspicious, all these are known to be unstable so I merged this PR (I need it for something else).

I am [re-running the job](https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/2280551460) to make sure these failures (or or most of them) are gone.

**Pull request merged**
