### PR TITLE
meta-mender-toradex-nxp: fix fw_env.config override

### PR DESCRIPTION
**Pull request by mirzak**
This is only valid for rocko as auto-patching works on master and sumo and no custom fw_env.config file is provided.

### CODE REVIEW

**Comment by drewmoseley** [comment]
In principle I have no problem with this but do we have any idea why this was needed now?  @alfrunes ping.

**Comment by drewmoseley** [comment]
@kacf can you take a look at the CI failure here? It looks related to the recent repository changes.

**Comment by mirzak** [comment]
@drewmoseley , you refresh patches are included in this PR and required as "rocko" and "rocko-next" are now identical in upstream Toradex repos.

**Comment by mirzak** [comment]
I started the jobs manually and I probably failed at that

**Comment by mirzak** [comment]
"vexpress-qemu_master_rocko_acceptance_tests" seems to fail with the same error it initially did when I opened the PR.

I guess we can not get rid of the "master_master" fails that I triggered which I should not have :)

**Comment by mirzak** [comment]
"vexpress-qemu_master_rocko_acceptance_tests" still failing. We can ignore the "maste_master" builds/test as that was unintentionally triggered by me.

**Comment by drewmoseley** [comment]
@mirzak I submitted https://github.com/mendersoftware/meta-mender/pull/631 which is identical to this but with a different commit hash.  The tests there succeeded so I think we can call this done.  The failures here are apparently CI infra related and not due to these changes.

**Comment by mirzak** [comment]
Thanks @drewmoseley

**Pull request merged**
