### PR TITLE
dunfell: Mender 2.6.0 release

### PR DESCRIPTION
**Pull request by lluiscampos**
* Add recipe mender-connect 1.0.0
Moving most of the logic of the old git recipe into an inc file, and
reworking the new git recipe as for other mender recipes.
Changelog: Title

* Add mender-client and mender-artifact new recipes
Changelog: Add recipe mender-client 2.5.0
Changelog: Add recipe mender-artifact 3.5.0

* Revert "Temporarily down-prioritize mender-binary-delta 1.2.0 in version sel."
This reverts commit 446dcc1ba224edf6e9dbc2fcf58ed1c0b5953a80.

### CODE REVIEW

**Comment by lluiscampos** [comment]
@kacf I tested locally: the images include `mender-connect` :heavy_check_mark:

**Review by kacf — APPROVED** [review]
> Make mender-connect dependent on mender-client. 

This commit should not be here. I think you need to rebase and make sure to omit it. It was force pushed in my PR because it didn't pass on master initially.

Other than that it looks good!

**Comment by lluiscampos** [comment]
> > Make mender-connect dependent on mender-client.
> 
> This commit should not be here. I think you need to rebase and make sure to omit it. It was force pushed in my PR because it didn't pass on master initially.

Even though I think I had your latest force-push, GitHub marked the file with a conflict so I don't see what happened. I did rebase now so it should be good.

> 
> Other than that it looks good!

Thanks

**Comment by lluiscampos** [comment]
Build 2.6.0 @ [Pipeline 244411343](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/244411343)

**Pull request merged**
