### PR TITLE
rocko: Add meta-mender-commercial layer

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
Starting build only for 2.1.0b1 release, as we are only interested in the commercial test.

ref: https://mender-jenkins.mender.io/job/mender-builder/4332/

**Comment by kacf** [comment]
I guess it's missing [this one](https://github.com/mendersoftware/meta-mender/commit/6252cb5f73f71adb4ff501c6faa9b39c19a4bc46).

**Comment by lluiscampos** [comment]
Latest build: https://mender-jenkins.mender.io/job/mender-builder/4346/

**Comment by lluiscampos** [comment]
Tests failed due to missing definition in meta-mender-core conf. See commit 968d6f3.

Even if it is low risk (the test passed on sumo PR https://github.com/mendersoftware/meta-mender/pull/816) I am running the tests once again to have it at least pass once in rocko. Ref: https://mender-jenkins.mender.io/job/mender-builder/4351/

**Comment by lluiscampos** [comment]
Test passed. Merging.

**Pull request merged**
