### PR TITLE
Pyro backports

### PR DESCRIPTION
**Pull request by drewmoseley**

### CODE REVIEW

**Comment by drewmoseley** [comment]
Finally.  All green.  I had to modify my cherry-pick of 'Provide build-conf files for testing in meta-mender' as that version was created with auto-patching. 
 In pyro (and morty) we had to add the meta-mender-beaglebone back into the bblayers.conf.  Details here https://github.com/mendersoftware/meta-mender/pull/498/commits/af226d1b27584793958f4bb5c0f1134d1dfa1910

**Comment by drewmoseley** [comment]
@kacf any idea why the vexpress-qemu_master_pyro_acceptance_tests is not working?  It looks like Jenkins is just killing it off for some reason.  I am fairly certain this passed at least once a few days ago.

**Comment by kacf** [comment]
Yeah, that's completely unrelated. I'm guessing it's a spurious happening. I have started a [new build](https://mender-jenkins.mender.io/job/mender-builder/180/) manually.

**Comment by drewmoseley** [comment]
Looks like I'll need https://github.com/mendersoftware/meta-mender/pull/512/commits/18cf71aefb629726f4d25ecee3d1669759b59b1b as well.  Cherry picking now.

**Comment by drewmoseley** [comment]
Hmm.  Different error this time but still seems unrelated to this PR content:
{quote}
17:05:11 The directory '/home/jenkins/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
17:05:11 The directory '/home/jenkins/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
17:05:11 Collecting Fabric (from -r /home/jenkins/workspace/yoctobuild/meta-mender/tests/acceptance/requirements.txt (line 1))
17:06:12 Exception:
17:06:12 Traceback (most recent call last):
17:06:12   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
17:06:12     status = self.run(options, args)
17:06:12   File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
17:06:12     requirement_set.prepare_files(finder)
17:06:12   File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
17:06:12     ignore_dependencies=self.ignore_dependencies))
17:06:12   File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 577, in _prepare_file
17:06:12     session=self.session, hashes=hashes)
17:06:12   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 810, in unpack_url
17:06:12     hashes=hashes
17:06:12   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 649, in unpack_http_url
17:06:12     hashes)
17:06:12   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 842, in _download_http_url
17:06:12     stream=True,
17:06:12   File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 480, in get
17:06:12     return self.request('GET', url, **kwargs)
17:06:12   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 378, in request
17:06:12     return super(PipSession, self).request(method, url, *args, **kwargs)
17:06:12   File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 468, in request
17:06:12     resp = self.send(prep, **send_kwargs)
17:06:12   File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 576, in send
17:06:12     r = adapter.send(request, **kwargs)
17:06:12   File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 46, in send
17:06:12     resp = super(CacheControlAdapter, self).send(request, **kw)
17:06:12   File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py", line 376, in send
17:06:12     timeout=timeout
17:06:12   File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 610, in urlopen
17:06:12     _stacktrace=sys.exc_info()[2])
17:06:12   File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 228, in increment
17:06:12     total -= 1
17:06:12 TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
17:06:12 You are using pip version 8.1.1, however version 10.0.1 is available.
17:06:12 You should consider upgrading via the 'pip install --upgrade pip' command.
17:06:12 ++ testFinished
17:06:12 ++ testFinished
17:06:12 + testFinished
17:06:12 ++ ret=1
17:06:12 ++ '[' -f /home/jenkins/stop_slave ']'
17:06:12 ++ exit 1
17:06:12 Build step 'Execute shell' marked build as failure
17:06:14 Performing Post build task...
17:06:14 Match found for : : True
17:06:14 Logical operation result is TRUE
17:06:14 Running script  : docker rm -v -f `docker ps -q`
17:06:14 docker system prune -f -a
17:06:14 [yoctobuild] $ /bin/sh -xe /tmp/jenkins1434607139466485069.sh
17:06:14 + docker ps -q
17:06:15 + docker rm -v -f
17:06:15 "docker rm" requires at least 1 argument.
17:06:15 See 'docker rm --help'.
17:06:15 
17:06:15 Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...] [flags]
17:06:15 
17:06:15 Remove one or more containers
17:06:16 POST BUILD TASK : FAILURE
17:06:16 END OF POST BUILD TASK : 0
17:06:16 Finished: FAILURE
{quote}

Looks like some kind of tooling issue related python/pip versions.

**Comment by kacf** [comment]
That's really weird. I cannot reproduce this outside the build, not even if I use the exact same Jenkins image from Google Cloud. Could it be a temporary messup from upstream? I'm retrying just to see if this goes away on its own.

**Comment by kacf** [comment]
https://mender-jenkins.mender.io/job/mender-builder/192/

**Comment by drewmoseley** [comment]
Odd.  It's all green here but the job shows a failure in https://mender-jenkins.mender.io/job/mender-builder/label=googlecloud%20&&%20mender_qemux86_64_uefi_grub%20&&%20mender_servers/192/

Although I'm not too worried about qemux86_64 on this branch.

**Comment by kacf** [comment]
Yes, but this is no surprise. It's trying to build x86, which is missing from pyro. Just ignore that one and enjoy the rest of the green-ness! :-)

**Comment by drewmoseley** [comment]
Yay.  Finally merging.  Pyro is up to date.
Now to figure out the other CI issues.

**Pull request merged**
