### PR TITLE
fix: Remove metadata_csum fix which is not needed anymore.

### PR DESCRIPTION
**Pull request by kacf**
It also breaks for some systems apparently.

Changelog: Fix rare mounting errors like these:
```
kernel: EXT4-fs error (device mmcblk0p6): ext4_mb_generate_buddy:1141: group 35, block bitmap and bg descriptor inconsistent: 32766 vs 32768 free clusters
```

Ticket: MEN-6027

### CODE REVIEW

**Review by lluiscampos — APPROVED** [review]
Based on the Git history of this fix, it is about time to remove it :+1:

**Comment by kacf** [comment]
@lluiscampos: Can you recheck? This required an additional fix I did not anticipate.

**Comment by kacf** [comment]
@lluiscampos: Ping

**Review by lluiscampos — APPROVED** [review]
Sorry that I missed the first ping. It looks good to me.

Additionally, based on your latest findings, should we remove [this warning](https://github.com/mendersoftware/mender-convert/blob/989d7df4b3f58aa20381a4ed07da914552393903/mender-convert-modify#L203)?

**Comment by kacf** [comment]
Good call, added here: https://github.com/mendersoftware/mender-convert/pull/659

**Pull request merged**
