### PR TITLE
Dunfell yocto check layer changes

### PR DESCRIPTION
**Pull request by drewmoseley**
# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits have a [`Changelog`](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

dunfell yocto-check-layer changes.

### CODE REVIEW

**Comment by kacf** [comment]
Just FYI, this is a followup from #1037.

**Comment by kacf** [comment]
Nice work, @drewmoseley! This is looking good to me. Apparently there are some test failures, but I can't immediately see why. I'll take a look at it ASAP though.

I'll focus on getting this one merged first, since this is ultimately what will go into meta-mender/master (which is still based on poky/dunfell). Afterwards we can take a look at the difference between this one and [the one you submitted to master-next](https://github.com/mendersoftware/meta-mender/pull/1083).

**Comment by lluiscampos** [comment]
@drewmoseley @kacf Short summary on the status of this PR.

Last attempted build ([here](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/194552046)) resulted on pass on all platforms except raspberrypi family, so we are getting closer! I launched yet another PR, with a fix for raspberrypi builds, and I think that should be the last thing :)

The fix itself (workaround, really) I am not confident about and I need yocto experts to look at it; see [this commit](https://github.com/mendersoftware/meta-mender/pull/1097/commits/77545b5379aa88c534e03920f61db8012f0f93ed). I tried with a similar statement (only affecting raspberrypi machine) on `meta-mender-raspberrypi-demo/recipes-core/psplash/psplash_git.bbappend` instead, but it didn't work... What is the right thing to do here?

**Comment by lluiscampos** [comment]
> @drewmoseley @kacf Short summary on the status of this PR.
> 
> Last attempted build ([here](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/194552046)) resulted on pass on all platforms except raspberrypi family, so we are getting closer! I launched yet another PR, with a fix for raspberrypi builds, and I think that should be the last thing :)
> 
> The fix itself (workaround, really) I am not confident about and I need yocto experts to look at it; see [this commit](https://github.com/mendersoftware/meta-mender/pull/1097/commits/77545b5379aa88c534e03920f61db8012f0f93ed). I tried with a similar statement (only affecting raspberrypi machine) on `meta-mender-raspberrypi-demo/recipes-core/psplash/psplash_git.bbappend` instead, but it didn't work... What is the right thing to do here?

Discussed [in the other PR](https://github.com/mendersoftware/meta-mender/pull/1097#discussion_r495809946).

**Comment by lluiscampos** [comment]
Merged at #1097 :tada:

**Pull request closed without merging**
