### PR TITLE
raspberrypi: u-boot: adjust mender patches for 2016.11

### PR DESCRIPTION
**Pull request by mirzak**
rpi-common.h has been renamed to rpi.h.

While at it changed mender.io occurrences to mender.

Signed-off-by: Mirza Krak <mirza.krak@gmail.com>

### CODE REVIEW

**Comment by mirzak** [comment]
Sure, will update filename to. I will then separate this in to two patches. One for u-boot fix, second pedantic renames

**Comment by mirzak** [comment]
Updated!

**Comment by mirzak** [comment]
Got one more patch pending for this pull-request

**Comment by mirzak** [comment]
And it is in.

**Comment by kacf** [comment]
Thanks!

**Pull request merged**
