### PR TITLE
Avoid populating rootfs partition B to save space when compressing.

### PR DESCRIPTION
**Pull request by kacf**
Original code by: Ehson Hussain <ehsonhussain@gmail.com>

Changelog: Title

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Comment by ahsanhussain** [comment]
Not only space, it also reduces build time, transfer and deployment time e.g. to flash on-board eMMC etc. I couldn't think of a good reason either to have the partition B populated in the first deployment but thought you guys might have a use case; thus did it conditionally. Would be great if it can be made the default option.

**Comment by ahsanhussain** [comment]
With these CI pipelines failing, is there a chance to get this merged?

**Comment by kacf** [comment]
I think they are just spurious failures. I'll rerun once more just to be safe though. For my own future reference, the original run is [here](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/404944244).

@mender-test-bot start pipeline

**Comment by kacf** [comment]
I have no clue what the pending job statuses are. The [pipeline passed](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/409089935).

**Comment by kacf** [comment]
@ahsanhussain: Done! I think this can be cherry-picked to dunfell as well, but I will do that separately as part of the monthly update.

**Comment by ahsanhussain** [comment]
@kacf thank you, I'll be waiting. :)

**Pull request merged**
