### PR TITLE
(ignore) feat: generate a bootstrap artifact

### PR DESCRIPTION
**Pull request by oleorhagen**

### CODE REVIEW

**Comment by oleorhagen** [comment]
Build started.
Link: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/631612353

**Comment by oleorhagen** [comment]
Build started.
Link: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/632041729

**Comment by oleorhagen** [comment]
Build started.
Link: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/632044377

**Comment by oleorhagen** [comment]
Build started.
Link: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/634921703

**Comment by lluiscampos** [comment]
Closing in favor of #1796

**Pull request closed without merging**
