### PR TITLE
MEN-2048: Fix `MENDER_GRUB_STORAGE_DEVICE` variable not being respected.

### PR DESCRIPTION
**Pull request by kacf**
Changelog: Title

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
Documentation will come separately through [MEN-1992](https://tracker.mender.io/browse/MEN-1992).

**Comment by estenberg** [comment]
Thanks! I am trying to test but get some (seemingly unrelated) errors of fetching linux-intel. Hope it is intermittent so will retry tomorrow.

**Comment by estenberg** [comment]
Bad news: meta-intel is broken (https://github.com/intel/linux-intel-lts/issues/4).
Good news: Your patch works flawlessly!

Tested on Minnowboard turbot with these storage settings:

MENDER_STORAGE_DEVICE = "/dev/mmcblk2"
MENDER_GRUB_STORAGE_DEVICE = "hd0"

Used meta-mender sumo with the commit from this PR cherry-picked.

**Comment by estenberg** [comment]
Would be awesome if this can go into sumo as well :)

**Comment by kacf** [comment]
> Would be awesome if this can go into sumo as well :)

It will!

**Pull request merged**
