### PR TITLE
Mender 2.7.0 components

### PR DESCRIPTION
**Pull request by kacf**

### CODE REVIEW

**Comment by kacf** [comment]
@mender-test-bot start pipeline

**Review by lluiscampos — CHANGES_REQUESTED** [review]
We should now revert https://github.com/mendersoftware/meta-mender/commit/346f222c25f3e8f696d3f4187eb63be8c32725e6 in master.

**Review by lluiscampos — APPROVED** [review]
Well, as all checks passed, I am also okey with merging as-is and following up independently. Approving.

**Comment by kacf** [comment]
@lluiscampos: Good catch! Submitted [here](https://github.com/mendersoftware/meta-mender/pull/1345).

**Pull request merged**
