### PR TITLE
mender: Setup rootfs partitions in automount blacklist.

### PR DESCRIPTION
**Pull request by drewmoseley**
Changelog: None
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by drewmoseley** [comment]
@lluiscampos this is needed for a customer project on this branch. It's been merged in master already but rather than wait for you to backport, I went ahead and did this one in particular.

**Comment by lluiscampos** [comment]
Great! Thanks. :+1: 

Starting the builds for both 1.7.x and 2.0.x

**Comment by lluiscampos** [comment]
@kacf The build for 2.0.x is failing due to license errors. See [Jenkins build 3413](https://mender-jenkins.mender.io/job/mender-builder/3413/), can you please verify that the parameters are correct?

I don't see where the problem is, as `rocko` has been build previously with 2.0.x

**Comment by kacf** [comment]
I'm not sure either, but shouldn't you build 2.0.0 and 1.7.1 rather than 2.0.x and 1.7.x? Or are you keeping the checksums of the Git recipe up to date?

**Comment by lluiscampos** [comment]
> I'm not sure either, but shouldn't you build 2.0.0 and 1.7.1 rather than 2.0.x and 1.7.x? [...]

Of course! That was my mistake ;)

**Comment by lluiscampos** [comment]
Everything passed now

**Pull request merged**
