### PR TITLE
Scarthgap cherry-picks

### PR DESCRIPTION
**Pull request by kacf**

### CODE REVIEW

**Comment by TheYoctoJester** [comment]
@kacf thoughts on also picking 46f7b9d76fe81bc2f79ff6ee260c9178011fc1df?

**Review by lluiscampos — APPROVED** [review]

**Comment by lluiscampos** [comment]
> @kacf thoughts on also picking [46f7b9d](https://github.com/mendersoftware/meta-mender/commit/46f7b9d76fe81bc2f79ff6ee260c9178011fc1df)?

I can take this in the upcoming regular update of the branch(es). Generally we wouldn't port features but this one is for testing so it shouldn't be a problem for users.

The current PR I understand is just to support testing `mender-update-orchestrator`.

**Comment by kacf** [comment]
> > @kacf thoughts on also picking [46f7b9d](https://github.com/mendersoftware/meta-mender/commit/46f7b9d76fe81bc2f79ff6ee260c9178011fc1df)?
> 
> I can take this in the upcoming regular update of the branch(es). Generally we wouldn't port features but this one is for testing so it shouldn't be a problem for users.
> 
> The current PR I understand is just to support testing `mender-update-orchestrator`.

That's fine, I can do it, I need to re-test anyway.

**Comment by lluiscampos** [comment]
I already merged the last commit in:
* https://github.com/mendersoftware/meta-mender/pull/2187

**Pull request merged**
