### PR TITLE
MEN-4292: Rename mender-shell to mender-connect

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: none

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Comment by tranchitella** [comment]
Depends on: https://github.com/mendersoftware/mender-image-tests/pull/35

**Comment by oleorhagen** [comment]
Could you not add the updates submodule to this PR?

**Comment by tranchitella** [comment]
> Could you not add the updates submodule to this PR?

I don't think so, because my commit is in another repo (my fork). I may be wrong, though. I'm not an expert with git submodules.

**Comment by oleorhagen** [comment]
> > Could you not add the updates submodule to this PR?
> 
> I don't think so, because my commit is in another repo (my fork). I may be wrong, though. I'm not an expert with git submodules.

Yes, but it would allow you to run the tests here though

**Comment by tranchitella** [comment]
I'll try to push my change in a branch in the main repo and reference the commit from there, let's see...

**Review by lluiscampos — CHANGES_REQUESTED** [review]
The rename requires a `Changelog` tag, as `mender-shell` recipes have been partially released in dunfell/zeus/warrior branches

**Comment by tranchitella** [comment]
> The rename requires a `Changelog` tag, as `mender-shell` recipes have been partially released in dunfell/zeus/warrior branches

Added a Changelog tag to the first commit.

**Review by lluiscampos — APPROVED** [review]

**Pull request merged**
