### PR TITLE
Upgrade vendored U-Boot recipe to version with vexpress upstreamed.

### PR DESCRIPTION
**Pull request by kacf**
This is mainly for validation purposes, to make sure their fixes do
not break our use case.

In addition to at least 1f7e71ba6c9142 and abf945f36ec6f, this should
be reverted once we move to a new stable poky branch.

Changelog: None

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
@mender-test-bot start pipeline

**Comment by kacf** [comment]
@mender-test-bot start pipeline

**Comment by kacf** [comment]
Cancelled run due to GCP capacity, will rerun tomorrow.

**Comment by kacf** [comment]
@mender-test-bot start pipeline

**Comment by kacf** [comment]
@mender-test-bot start pipeline

**Review by lluiscampos — APPROVED** [review]
ACK

**Pull request merged**
