### PR TITLE
chore: Fix warnings

### PR DESCRIPTION
**Pull request by lluiscampos**
* chore(test_delta_update_module.py): Migrate from deprecated distutils
    Clears `DeprecationWarning`. See:
    https://peps.python.org/pep-0632/#migration-advice

* chore(test_build.py): Fix syntax with a literal
    Clears `SyntaxWarning`: "is not" with a literal.

### CODE REVIEW

**Comment by lluiscampos** [comment]
See also:
* https://github.com/mendersoftware/mender-image-tests/pull/76

**Review by kacf — APPROVED** [review]
> Note: Not signing to drop this commit before merge

Why do you want to drop it?

**Comment by lluiscampos** [comment]
> > Note: Not signing to drop this commit before merge
> 
> Why do you want to drop it?

Just a formality - I wanted to merge https://github.com/mendersoftware/mender-image-tests/pull/76 and then get here the dependabot auto-generated commit.

**Comment by lluiscampos** [comment]
Full acceptance tests build @ [Pipeline 692571683](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/692571683).

The last force-push updated the submodule git sha with no code changes, so no running the integration pipeline again.

**Review by oleorhagen — COMMENTED** [review]
Yes! I've been 'planning' on getting around to this for ages

**Pull request merged**
