### PR TITLE
allow IMAGE_BOOTLOADER_BOOTSECTOR_OFFSET to be aligend to 512 bytes

### PR DESCRIPTION
**Pull request by mirzak**
This is a partial back-port of:

     33225086db3 ("MEN-1845: Implement x86 BIOS support together with GRUB")

Which removed the limitation that the IMAGE_BOOTLOADER_BOOTSECTOR_OFFSET must
be 1kB aligned. It is useful to get rid of this limitation as there are some
boards/SoCs that require the bootloader to be at the first block (512 bytes / block)

Changelog: Title

Signed-off-by: Mirza Krak <mirza.krak@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
@mirzak: Tip: If you want to avoid the license errors in Jenkins, you can run this manually with the release tool and a released version. This avoids the unstable md5sums in the Git version:

```
integration/extra/release_tool.py -b 1.7.0 --pr meta-mender/707
```

**Comment by kacf** [comment]
You might have to change some other parameters too, to match rocko, such as `POKY_REV`.

**Comment by mirzak** [comment]
> integration/extra/release_tool.py -b 1.7.0 --pr meta-mender/707

What will this do? Create a commit?

**Comment by drewmoseley** [comment]
Once we retry with the jenkins changes and go all green I'll merge this.

**Comment by mirzak** [comment]
The retry is in progress, only acceptance tests left

**Comment by mirzak** [comment]
The 1.7.0 builds/tests are all green.

**Pull request merged**
