### PR TITLE
Remove e2fsprogs patch to fix bmaptool issue.

### PR DESCRIPTION
**Pull request by hacpa**
This patch, which removes  metadata_csum from the available ext4 features, breaks flashing with bmaptool.
It was created at a time when tools such as fsck.ext4 and tune2fs did not handle that feature.
Nowadays, these tools have been updated and it is safe to remove the patch.

Changelog: Title

Signed-off-by: Pascal Hache <hacpa@touchtunes.com>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits have a [`Changelog`](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Comment by hacpa** [comment]
This change is tested only against the "zeus" branch.

**Review by kacf — APPROVED** [review]
Thanks! I will run this through our full test suite.

**Comment by kacf** [comment]
It looks like there are multiple problem with bringing back `metadata_csum`. Two key tests that fail are:

* Snapshotting a live filesystem using `mender snapshot dump` command produces a filesystem for which fsck outputs: `/dev/mmcblk0p3: Journal superblock is corrupt.`
* Checksum of a filesystem mounted read-only is no longer stable, which is needed for binary delta updates to work.

Unless you feel like digging into why these happen, I think we have to stick with `metadata_csum` being off for the time being. :-(

For reference, these are exceptions we got in Gitlab (the project is private so externals can't see it):

```
self = <test_snapshot.TestSnapshot object at 0x7f4efbe91f98>
compression = ('', '>')
bitbake_variables = {'ABIEXTENSION': 'eabi', 'ABIEXTENSION_class-nativesdk': '', 'ALLOW_EMPTY_core-image-minimal-dbg': '1', 'ALLOW_EMPTY_core-image-minimal-dev': '1', ...}
connection = <Connection host=localhost user=root port=8822>

    @pytest.mark.min_mender_version("2.2.0")
    @pytest.mark.only_with_image("uefiimg", "sdimg", "biosimg", "gptimg")
    @pytest.mark.parametrize("compression", [("", ">"), ("-C gzip", "| gunzip -c >")])
    def test_basic_snapshot(self, compression, bitbake_variables, connection):
        try:
            (active, passive) = determine_active_passive_part(
                bitbake_variables, connection
            )
    
            # Wipe the inactive partition first.
            connection.run("dd if=/dev/zero of=%s bs=1M count=100" % passive)
    
            # Dump what we currently have to the inactive partition.
            connection.run(
                "mender snapshot dump %s %s %s"
                % (compression[0], compression[1], passive)
            )
    
            # Make sure this looks like a sane filesystem.
>           connection.run("fsck.ext4 -p %s" % passive)

test_snapshot.py:42: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
<decorator-gen-3>:2: in run
    ???
/usr/local/lib/python3.6/dist-packages/fabric/connection.py:30: in opens
    return method(self, *args, **kwargs)
/usr/local/lib/python3.6/dist-packages/fabric/connection.py:721: in run
    return self._run(self._remote_runner(), command, **kwargs)
/usr/local/lib/python3.6/dist-packages/invoke/context.py:101: in _run
    return runner.run(command, **kwargs)
/usr/local/lib/python3.6/dist-packages/invoke/runners.py:363: in run
    return self._run_body(command, **kwargs)
/usr/local/lib/python3.6/dist-packages/invoke/runners.py:422: in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <fabric.runners.Remote object at 0x7f4efbc23be0>

    def _finish(self):
        # Wait for subprocess to run, forwarding signals as we get them.
        try:
            while True:
                try:
                    self.wait()
                    break  # done waiting!
                # Don't locally stop on ^C, only forward it:
                # - if remote end really stops, we'll naturally stop after
                # - if remote end does not stop (eg REPL, editor) we don't want
                # to stop prematurely
                except KeyboardInterrupt as e:
                    self.send_interrupt(e)
                # TODO: honor other signals sent to our own process and
                # transmit them to the subprocess before handling 'normally'.
        # Make sure we tie off our worker threads, even if something exploded.
        # Any exceptions that raised during self.wait() above will appear after
        # this block.
        finally:
            # Inform stdin-mirroring worker to stop its eternal looping
            self.program_finished.set()
            # Join threads, storing inner exceptions, & set a timeout if
            # necessary. (Segregate WatcherErrors as they are "anticipated
            # errors" that want to show up at the end during creation of
            # Failure objects.)
            watcher_errors = []
            thread_exceptions = []
            for target, thread in six.iteritems(self.threads):
                thread.join(self._thread_join_timeout(target))
                exception = thread.exception()
                if exception is not None:
                    real = exception.value
                    if isinstance(real, WatcherError):
                        watcher_errors.append(real)
                    else:
                        thread_exceptions.append(exception)
        # If any exceptions appeared inside the threads, raise them now as an
        # aggregate exception object.
        # NOTE: this is kept outside the 'finally' so that main-thread
        # exceptions are raised before worker-thread exceptions; they're more
        # likely to be Big Serious Problems.
        if thread_exceptions:
            raise ThreadException(thread_exceptions)
        # Collate stdout/err, calculate exited, and get final result obj
        result = self._collate_result(watcher_errors)
        # Any presence of WatcherError from the threads indicates a watcher was
        # upset and aborted execution; make a generic Failure out of it and
        # raise that.
        if watcher_errors:
            # TODO: ambiguity exists if we somehow get WatcherError in *both*
            # threads...as unlikely as that would normally be.
            raise Failure(result, reason=watcher_errors[0])
        # If a timeout was requested and the subprocess did time out, shout.
        timeout = self.opts["timeout"]
        if timeout is not None and self.timed_out:
            raise CommandTimedOut(result, timeout=timeout)
        if not (result or self.opts["warn"]):
>           raise UnexpectedExit(result)
E           invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
E           
E           Command: 'fsck.ext4 -p /dev/mmcblk0p3'
E           
E           Exit code: 1
E           
E           Stdout: already printed
E           
E           Stderr: already printed

/usr/local/lib/python3.6/dist-packages/invoke/runners.py:489: UnexpectedExit
```

and the other one:

```
self = <test_delta_update_module.TestDeltaUpdateModule object at 0x7f4ef9588fd0>
setup_board = None
prepared_test_build = {'bitbake_corebase': '/builds/Northern.tech/Mender', 'build_dir': '/builds/Northern.tech/Mender/build-vexpress-qemu/test-build-xcskc1w8'}
bitbake_variables = {'ABIEXTENSION': 'eabi', 'ABIEXTENSION_class-nativesdk': '', 'ALLOW_EMPTY_core-image-minimal-dbg': '1', 'ALLOW_EMPTY_core-image-minimal-dev': '1', ...}
bitbake_image = 'core-image-full-cmdline'
connection = <Connection host=localhost user=root port=8822>
http_server = '10.0.2.2:8000', board_type = 'vexpress-qemu', use_s3 = False
s3_address = 's3.amazonaws.com'

    @pytest.mark.only_with_image("ext4")
    def test_runtime_checksum(
        self,
        setup_board,
        prepared_test_build,
        bitbake_variables,
        bitbake_image,
        connection,
        http_server,
        board_type,
        use_s3,
        s3_address,
    ):
        """Check that the checksum of the running root filesystem is what we
        expect. This is important in order for it to match when applying a delta
        update.
    
        """
    
        if (
            "read-only-rootfs"
            not in bitbake_variables["IMAGE_FEATURES"].strip().split()
        ):
            pytest.skip("Only works when using read-only-rootfs IMAGE_FEATURE")
    
        build_image(
            prepared_test_build["build_dir"],
            prepared_test_build["bitbake_corebase"],
            bitbake_image,
            ['IMAGE_INSTALL_append = " mender-binary-delta"'],
            [
                'BBLAYERS_append = " %s/../meta-mender-commercial"'
                % bitbake_variables["LAYERDIR_MENDER"]
            ],
        )
    
        image = latest_build_artifact(
            prepared_test_build["build_dir"], "core-image*.mender"
        )
    
        Helpers.install_update(
            image, connection, http_server, board_type, use_s3, s3_address,
        )
    
        reboot(connection)
    
        run_after_connect("true", connection)
        (active, _) = determine_active_passive_part(bitbake_variables, connection)
    
        connection.run("mender -commit")
    
        # Check that checksum of the currently mounted rootfs matches that
        # of the artifact which we just updated to.
        output = connection.run("sha256sum %s" % active)
        rootfs_sum = output.stdout.split()[0]
        output = subprocess.check_output(
            "mender-artifact read %s" % image, shell=True
        ).decode()
        match = re.search("checksum: *([0-9a-f]+)", output)
        assert match is not None, (
            "Could not find checksum in mender-artifact output: %s" % output
        )
        artifact_sum = match.group(1)
>       assert rootfs_sum == artifact_sum
E       AssertionError: assert 'd6d938fa21df...30f5263a58f57' == 'df53f5153c8f...6e576bec6299b'
E         - d6d938fa21dfbc16269e2eaf572cb99bbe08d487383d69f983230f5263a58f57
E         + df53f5153c8f8ce52d05db3f3027a3465add1f56796db34c7366e576bec6299b

commercial/test_delta_update_module.py:119: AssertionError
```

**Comment by hacpa** [comment]
@kacf I'm afraid that I am unfamiliar with the snapshot and binary update features. I cannot help with that, other than giving the hypothesis that these features (or the tests setups themselves) may be using the "old tools" (fsck, etc) that were mentioned in the original changeset that this PR reverts, which do not support metadata_csum.

If you must, you may close this PR.

Quick question: was that force-push on my fork yesterday intentional? If not (and you choose to close the PR), I might want to revert to the old commit.

**Comment by kacf** [comment]
>  I'm afraid that I am unfamiliar with the snapshot and binary update features. I cannot help with that, other than giving the hypothesis that these features (or the tests setups themselves) may be using the "old tools" (fsck, etc) that were mentioned in the original changeset that this PR reverts, which do not support metadata_csum.

You may be on to something actually. I noticed that the test does not inherit the Bitbake environment which contains fsck. Let me retry it.

It's not going to help for the second problem, but this problem is specific to read-only filesystems, so if everything else works, we could make an exception there.

> Quick question: was that force-push on my fork yesterday intentional? If not (and you choose to close the PR), I might want to revert to the old commit.

It was just a rebase. The PR was initially failing because it was out of date. But please allow me to push some more. I will try the fsck environment fix as well, to see if that helps.

**Comment by kacf** [comment]
```
root@qemux86-64:~# mender snapshot dump > /dev/hda3 
................................ 100% 229376 KiB
root@qemux86-64:~# fsck.ext4 -p -f /dev/hda3
/dev/hda3: Journal superblock is corrupt.
FIXED.
/dev/hda3: 6565/57344 files (1.0% non-contiguous), 163312/229376 blocks
root@qemux86-64:~# fsck.ext4 -V
e2fsck 1.45.4 (23-Sep-2019)
	Using EXT2FS Library version 1.45.4, 23-Sep-2019
root@qemux86-64:~# 
```

No, unfortunately it does not work. Even fsck inside the image itself detects the superblock as corrupt. I think we will have to close this PR.

Feel free to push to your branch, I won't use it any more.

**Pull request closed without merging**
