### PR TITLE
(verify) MEN-7298

### PR DESCRIPTION
**Pull request by lluiscampos**
To be merged as part of https://github.com/mendersoftware/meta-mender/pull/2099.

### CODE REVIEW

**Comment by lluiscampos** [comment]
@TheYoctoJester @danielskinstad Only the last two commits need review.

**Comment by lluiscampos** [comment]
> @TheYoctoJester @danielskinstad Only the last two commits need review.

Three :smiley:

**Review by TheYoctoJester — APPROVED** [review]
Nitpick: the two changes are functionally independent and could/should be separate commits. But I'm fine with keeping it if you think its okay.

**Comment by lluiscampos** [comment]
I'll apply the feedback directly on #2099. Closing this one

**Pull request closed without merging**
