### PR TITLE
Make sure that correct version of u-boot will be used.

### PR DESCRIPTION
**Pull request by pasinskim**
Each Yocto version is updating u-boot. We need to make sure that we can
apply custom patches to support both beaglebone and vexpress-quemu.
For this we are using u-boot v2015.10 and this is defined as
PREFFERED_VERSION in mender-install class.

### CODE REVIEW

**Comment by pasinskim** [comment]
@kacf can you take a brief look at this one to make sure I am not doing anything stupid here?

**Comment by kacf** [comment]
Most of this is copied directly from poky, I assume?

**Comment by pasinskim** [comment]
@kacf u-boot is a poky copy, indeed.

**Comment by kacf** [comment]
Ok, it looks good to me.

**Pull request merged**
