### PR TITLE
zeus update following dunfell-v2021.01

### PR DESCRIPTION
**Pull request by lluiscampos**
Porting #1248, #1261, #1263, #1266, #1270, #1273, #1275, #1276, #1278... and cherry-picking #1300.

### CODE REVIEW

**Review by kacf — APPROVED** [review]

**Comment by lluiscampos** [comment]
Builds:
* For Mender 2.4.2 @ [Pipeline 258233567](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/258233567)
* For Mender 2.6.0 @ [Pipeline 258233727](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/258233727)

**Comment by lluiscampos** [comment]
Note to self: `test_perform_update` needs to set with `min_mender_version`. Running the test on Mender 2.4.2 triggers:
```
This version of mender-binary-delta-generator requires mender-artifact version 3.5.0 or higher to be installed somewhere in PATH.
```

**Comment by lluiscampos** [comment]
> Note to self: `test_perform_update` needs to be set with `min_mender_version`. Running the test on Mender 2.4.2 triggers:

Fixed now. Repeating build for Mender 2.4.2 @ [Pipeline 258595529](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/258595529).

**Comment by lluiscampos** [comment]
@kacf Please have a look at the last commit here, and see if it makes sense to you.

**Review by kacf — APPROVED** [review]
Looks good, thanks for handling!

**Pull request merged**
