### PR TITLE
Update feature branch + MEN-4187: meta-mender-demo: install mender-shell     

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
Build @ [Pipeline 224392939](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/224392939)

**Comment by lluiscampos** [comment]
The `mender-shell` recipe itself was in bad shape, have we ever built it in Yocto? Last force-push fixes the recipe.

New build @ [Pipeline 224424612](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/224424612)

**Comment by lluiscampos** [comment]
Next, `test_dbus.py` needed an update after test framework upgrade.

New build (and probably not last) @ [Pipeline 224434472](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/224434472)

**Comment by lluiscampos** [comment]
`test_build` also needed an update after test framework upgrade.

New build @ [Pipeline 224620124](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/224620124)

**Review by kacf — APPROVED** [review]

**Comment by lluiscampos** [comment]
New build @ [Pipeline 224736356](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/224736356)

**Pull request merged**
