### PR TITLE
Meta mender aarch 64 support

### PR DESCRIPTION
**Pull request by Minipada**
This follows https://github.com/mendersoftware/meta-mender/pull/561 .
Commits are signed and I added the changelogs

### CODE REVIEW

**Comment by mirzak** [comment]
Thanks, will run this trough our integrations test.

**Comment by mirzak** [comment]
Test failed because you did not use the same identity for the sign-off-by as the author of the commit. Our tests are nit-picky :).

```
>           pytest.fail(e.output)
E           Failed: Checking range: HEAD --not origin/beaglebone_new_ci origin/daisy origin/krogoth origin/master origin/morty origin/pyro origin/rocko origin/stable origin/state-scripts-morty origin/sumo origin/test-ro-rootfs:
E           commit 0a7cf4293ed8d0abde67c406c2bb08166322312c
E           Author: David Bensoussan <minipada@gmail.com>
E           Date:   Fri Jul 27 14:21:55 2018 +0200
E           
E               fix: add mender-sd-image for aarch64
E               
E               Changelog: Fixed support for raspberrypi3-64 and aarch64
E               Signed-off-by: David Bensoussan <dbensoussan@synapticon.com>
E           
E           commit 9c4f0b72fa7edce52612e4970311ed62502737ce
E           Author: David Bensoussan <minipada@gmail.com>
E           Date:   Fri Jul 27 14:16:55 2018 +0200
E           
E               fix: use @@KERNEL_IMAGETYPE@@ instead of uImage
E               
E               Changelog: None
E               Signed-off-by: David Bensoussan <dbensoussan@synapticon.com>
E           Commit 0a7cf4293ed8d0abde67c406c2bb08166322312c is not signed off! Use --signoff with your commit.
E           Commit 9c4f0b72fa7edce52612e4970311ed62502737ce is not signed off! Use --signoff with your commit.
```

**Comment by mirzak** [comment]
Thanks, lets try the tests again.

**Comment by Minipada** [comment]
I appreciate the effort, thanks :)

**Comment by mirzak** [comment]
Good point, all checks have passed. 

Just need to verify that we did not break 32-bit and this can be merged. @Minipada if you are able to do it would be great. Otherwise I will do a quick run when I get around to it.

**Comment by mirzak** [comment]
Verified, rpi_32b still works as expected. Merging.

**Comment by Minipada** [comment]
@drewmoseley That's a good point.
I was out of office and didn't check. Thanks for testing it!

**Pull request merged**
