### PR TITLE
Rocko backports v2019.05

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by mirzak** [comment]
Did you forget about https://github.com/mendersoftware/meta-mender/pull/739?  :)

**Comment by lluiscampos** [comment]
@mirzak Yes, I did :weary: I'll port it to both sumo and rocko and rerun tests.

Sorry. And thank you for your attention to detail!

**Comment by mirzak** [comment]
Note that it is not needed for sumo (already fixed), only rocko

**Comment by lluiscampos** [comment]
> Note that it is not needed for sumo (already fixed), only rocko

Yes, I realized now while re-reading our private conversation of few days ago. Thanks.

**Comment by lluiscampos** [comment]
One failing test for 2.0.x build:

* TestFaultTolerance::test_update_image_recovery
  * Passes for qemux86_64_uefi_grub, fails for vexpress_qemu but passed for  -> Spurious failure

**Comment by kacf** [comment]
I will remove this test, see [here](https://github.com/mendersoftware/integration/pull/603). So you can consider it spurious.

**Pull request merged**
