### PR TITLE
mender: Quote bootargs for expansion with embedded variables. 

### PR DESCRIPTION
**Pull request by drewmoseley**
Changelog: none

Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by drewmoseley** [comment]
@kacf I put a version of this in Morty since I saw some issues with it there.  I am seeing similar behavior on a raspberrypi-cm platform.  I'm not sure why it's needed on some platforms and not others.  I suspect there is a UBoot fix or configuration that may be contributing to things.  Thoughts?

**Comment by kacf** [comment]
I think it's always better to quote than not to quote. I'll rerun this through Jenkins, I think it's just a hiccup, but given the nature of this fix it *could* be legit.

**Comment by drewmoseley** [comment]
@kacf how quickly can we get this merged back into rocko?  I need it for services.

**Comment by kacf** [comment]
I can do that right now. See #455.

**Pull request merged**
