### PR TITLE
[RFC] auto-reboot: Add systemd service to force an automatic reboot.

### PR DESCRIPTION
**Pull request by drewmoseley**
This allows us to simulate a bad device update to test rollback
capability.

Signed-off-by: Drew Moseley <drew.moseley@mender.io>

### CODE REVIEW

**Comment by drewmoseley** [comment]
@kacf any interest in this or something similar?

**Comment by kacf** [comment]
Ah, we are testing rollback functionality already! Check [this test](https://github.com/mendersoftware/meta-mender/blob/master/tests/acceptance/test_update.py#L117-L143).

**Comment by drewmoseley** [comment]
That only seems to work with QEMU right?  This recipe allows it to be tested/demoed on the Beaglebone using the full backend integration. Admittedly it's heavier-weight as it requires a Yocto rebuild but I have used it successfully for a demo that I put together.

**Comment by kacf** [comment]
No, all the client acceptance tests run for the Beaglebone as well (well, except for the fact that it's out of order right now, but that's unrelated to the test). We also have similar "broken image" tests in the integration repository, so this should be pretty well covered already.

**Comment by drewmoseley** [comment]
@kacf is there any way to use that artifact deployed through a backend instance to test the entire workflow?  I was able to do the standalone deployment but ultimately I'd like a demo setup through the backend.

Would this kind of change be better submitted through meta-mender-demo?

**Comment by kacf** [comment]
I'm not sure I understand what you're after... Ping me on Slack when you get the chance!

**Comment by drewmoseley** [comment]
OK.  I am able to test the rollback now using an image created similar to what is done here: https://github.com/mendersoftware/meta-mender/blob/master/tests/acceptance/test_update.py#L117-L143

This is no longer needed.

**Pull request closed without merging**
