### PR TITLE
[zeus] vexpress: Remove nonexistent kernel config options that issue warnings.

### PR DESCRIPTION
**Pull request by lluiscampos**
Commit missing from #1057

### CODE REVIEW

**Comment by lluiscampos** [comment]
@drewmoseley While reviewing zeus/warrior I saw that this commit was missing from your original PR. Was it intentional?

**Comment by lluiscampos** [comment]
Build @ [Pipeline 181731743](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/181731743)

**Review by kacf — APPROVED** [review]

**Comment by lluiscampos** [comment]
Interesting enough, the acceptance tests fail and timeout after 8h for vexpress jobs (I retried the run, the failure is consistent). I will be looking more into this later.

**Comment by lluiscampos** [comment]
> Not intentional but I'm not sure I saw the warnings on Zeus.

Not that I have seen the warnings neither, but the patch was ported to warrior so that was surprising to me.

> Interesting enough, the acceptance tests fail and timeout after 8h for vexpress jobs (I retried the run, the failure is consistent). I will be looking more into this later.

I honestly don't know that the problem is. The error is consistent. These two vepxress jobs fail in test `test_inventory.py::TestInventory::test_rootfs_type`, throwing the following error at boot:

```
Mounting [0;1;39m/data[0m...
[   21.260019] EXT4-fs (mmcblk0p4): Filesystem with huge files cannot be mounted RDWR without CONFIG_LBDAF
[[0;1;31mFAILED[0m] Failed to mount [0;1;39m/data[0m.
```

and making then the framework to hang until CI timeout (8 hours).

These errors, together with the fact that I don't have a good reason to port the patch to `zeus`, makes me conclude that it better to reject this PR.

**Pull request closed without merging**
