### PR TITLE
Remove several mender and mender-artifact artifact versions.

### PR DESCRIPTION
**Pull request by kacf**
Changelog: Remove mender-2.0.x and older, and mender-artifact 3.0.x
and older.

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Comment by lluiscampos** [comment]
Nice clean-up. I'll get this change also in warrior

**Comment by lluiscampos** [comment]
> I'll get this change also in warrior

Well, according to PR #772 we keep these recipes in warrior. Can we discuss this a bit? At least we could stop supporting 1.x in warrior (not yet released any tag there)

**Comment by mirzak** [comment]
> I'll get this change also in warrior

I do not think that we should. There are chances that people are still using 1.7 even if they are on warrior and we would break this. It is to late to clean up now :)

**Comment by lluiscampos** [comment]
> > I'll get this change also in warrior
> 
> I do not think that we should. There are chances that people are still using 1.7 even if they are on warrior and we would break this. It is to late to clean up now :)

I agree. We will remove it only in master

**Comment by kacf** [comment]
Yes, recipe removals are only done in master, in preparation for the next Yocto release.

**Comment by kacf** [comment]
Only known spurious errors. Merging.

**Pull request merged**
