### PR TITLE
chore(license): Update the mender license checksum

### PR DESCRIPTION
**Pull request by oleorhagen**
This is to account for the 2024 license year update.

### CODE REVIEW

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Review by lluiscampos — APPROVED** [review]

**Comment by oleorhagen** [comment]
> Hello 😺 I created a pipeline for you here: [Pipeline-1125509010](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/1125509010)
> Build Configuration Matrix

**Comment by oleorhagen** [comment]
> @mender-test-bot start pipeline

**Comment by lluiscampos** [comment]
@oleorhagen Fix only the mender client git recipe, the rest will be fixed here:
* https://github.com/mendersoftware/meta-mender/pull/2045/commits

Alternatively bring your commit to Fabio's PR and then run the pipeline once there.

**Comment by oleorhagen** [comment]
At least we know it works :)

**Pull request merged**
