### PR TITLE
chore: Append demo certificate from monorepo

### PR DESCRIPTION
**Pull request by alfrunes**
Adds the demo certificate from:
https://github.com/mendersoftware/mender-server/pull/110

### CODE REVIEW

**Review by lluiscampos — APPROVED** [review]
@alfrunes Thank you! I'll take care of adjusting the tests (and adding a changelog tag to your commit - this is a chore that we want to release)

**Comment by lluiscampos** [comment]
Build @ [Pipeline 1503185596](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/1503185596)

**Comment by lluiscampos** [comment]
New build (only re-running relevant build configuration) @ [1504774946](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/1504774946)

**Comment by alfrunes** [comment]
@lluiscampos Sorry. After receiving some feedback, I decided to import the certificate from integration and defer the domain/certificate change until next time we renew the demo certificate. https://github.com/mendersoftware/mender-server/pull/110

**Pull request closed without merging**
