### PR TITLE
warrior update following dunfell-v2021.01

### PR DESCRIPTION
**Pull request by lluiscampos**
Porting #1302 without the tests updates.

### CODE REVIEW

**Comment by lluiscampos** [comment]
Builds:
* Mender 2.4.2 @ [Pipeline 258755916](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/258755916)
* Mender 2.6.0 @ [Pipeline 258756143](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/258756143)

**Comment by lluiscampos** [comment]
New builds:
* Mender 2.4.2 @ [Pipeline 258815389](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/258815389)
* Mender 2.6.0 @ [Pipeline 258809710](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/258809710)

**Comment by lluiscampos** [comment]
New builds:
* Mender 2.4.2 @ [Pipeline 259110548](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/259110548)
* Mender 2.6.0 @ [Pipeline 259110580](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/259110580)

**Comment by lluiscampos** [comment]
Repeating integration tests for Mender 2.6.0 together with test fix https://github.com/mendersoftware/integration/pull/1218 @ [Pipeline 259160330](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/259160330)

**Comment by lluiscampos** [comment]
@kacf Ready for review now. Many commits needed some tweaking for warrior (mainly due to the mender-client/mender naming). Also have a close look at the last commit.

**Review by kacf — APPROVED** [review]
LGTM, nice fixing of the patch at the end there!

**Pull request merged**
