### PR TITLE
Fix RPI CM3 u-boot hang

### PR DESCRIPTION
**Pull request by nandra**
Changelog: Title

https://github.com/agherzan/meta-raspberrypi/pull/660

raspberrypi CM3 fails to boot (u-boot hangs) on 2020.01 and adding this
path fix an issue.

Signed-off-by: Marek Belisko <marek.belisko@open-nandra.com>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits have a [`Changelog`](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Comment by nandra** [comment]
Actually this fix is manually verified but I have some strange yocto build issue when building with this change:
```
ERROR: Nothing PROVIDES 'u-boot-default-script' (but /home/jenkins/mender-raspberrypi/build/../sources/meta-mender/meta-mender-core/recipes-bsp/u-boot/u-boot_2020.01.bb DEPENDS on or otherwise requires it)
ERROR: Required build target 'u-boot' has no buildable providers.
Missing or unbuildable dependency chain was: ['u-boot', 'u-boot-default-script']
```

Any ideas what causing this?

**Comment by drewmoseley** [comment]
@nandra  it looks like rpi-u-boot-scr is supposed to provide "u-boot-default-script" but somehow is not.  What happens if you just try to bitbake that recipe?  Maybe there is an error in there that will be instructive.

**Comment by nandra** [comment]
@drewmoseley I've tried but I got:
```
ERROR: Nothing PROVIDES 'u-boot-default-script'
```

Thanks.

**Comment by nandra** [comment]
@drewmoseley sorry for noise. It was caused by my own stupidity (I have some incompatible changes in meta-raspberrypi). Verifying now complete build with above fix. Thansk

**Comment by nandra** [comment]
Verified on RPI CM3 with this fix board boots fine. It is necessary only for zeus branch for dunfell there is fix already in meta-raspberrypi layer.

**Comment by mirzak** [comment]
@lluiscampos, can you help out with starting a CI run?

**Comment by lluiscampos** [comment]
Build at [Pipeline 174483356](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/174483356).

**Comment by lluiscampos** [comment]
@mirzak @nandra Any reason for this patch not to go to master/dunfell? I will re-submit it there and once tests pass I can backport to zeus

**Comment by lluiscampos** [comment]
Re-submitted to master in #1053

**Comment by nandra** [comment]
@lluiscampos in meta-raspberrypi dunfell this patch is present already. Not necessary to push it to master. Thanks.

**Comment by lluiscampos** [comment]
@nandra Ok, thanks.

**Comment by lluiscampos** [comment]
New build (for warrior) at [Pipeline 174530923](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/174530923).

**Comment by lluiscampos** [comment]
> New build (for warrior) at [Pipeline 174530923](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/174530923).

For zeus at [Pipeline 174555867](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/174555867).

(today is not my day...)

**Pull request merged**
