### PR TITLE
Update rpi setup

### PR DESCRIPTION
**Pull request by mirzak**
Update the documentation for the required options in local.conf. There have been some changes in meta-raspberrypi which we need to adjust to.

I have boot and update tested this on a RPi3.

This is only applicable on master branch and in upcoming rocko.

### CODE REVIEW

**Comment by mirzak** [comment]
Appreciate if you can take a look at this @drewmoseley. I know you mentioned that you where planning some changes in this area as well.

**Comment by drewmoseley** [comment]
This is exactly what I was planning only I hadn't had time to test it yet. Thanks for testing this. Looks good to me.

**Comment by GregorioDiStefano** [comment]
@mirzak can you rebase this off master? I wanted to test this PR in our CI with RPI3, but the support for it has only been added recently. Thanks!

**Comment by mirzak** [comment]
@GregorioDiStefano Rebase done.

Crossing my fingers that it will pass :)

**Comment by GregorioDiStefano** [comment]
@mirzak Thanks! This works! RPi3 is now bootable on master.

**Comment by GregorioDiStefano** [comment]
@mirzak @drewmoseley I'm gonna go ahead and merge this, as I need it to move forward

**Pull request merged**
