### PR TITLE
Add lmdb recipe

### PR DESCRIPTION
**Pull request by oleorhagen**
This is required for use with the mender-monitor client, which has a dependency
on the mdb_{dump,load} commands.

The recipe is a simple copy-paste from the lmdb recipe in meta-openembedded
master. But since it is not present in any of the releases we rely on, this will
have to be mirrored in our repository for compatibility with the old
releases (Dunfell, and Gatesgarth amongst them).

Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits have a [`Changelog`](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Comment by oleorhagen** [comment]
See https://northern-tech.slack.com/archives/C2D3HRU9M/p1628570937005100 for context

**Review by kacf — APPROVED** [review]
Can you also create a ticket to remove this recipe, and set the FixVersion to yocto-3.5?

**Comment by oleorhagen** [comment]
> Can you also create a ticket to remove this recipe, and set the FixVersion to yocto-3.5?

Smart! I was just pondering how to handle the deprecation.

**Comment by oleorhagen** [comment]
Follow up: https://tracker.mender.io/browse/MEN-4937

**Comment by lluiscampos** [comment]
Aren't we missing [this `run-ptest` script](http://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-dbs/lmdb/files/run-ptest)? Otherwise we can modify the recipe to not inherit ptest and remove also the `do_install_ptest`

**Review by lluiscampos — CHANGES_REQUESTED** [review]
You need to add the `lmdb` dependency on `mender-monitor` recipe

**Review by lluiscampos — APPROVED** [review]

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by merlin-northern** [comment]
@oleorhagen tested. works like a charm!

**Pull request merged**
