### PR TITLE
Back to testing mender as a standalone application

### PR DESCRIPTION
**Pull request by GregorioDiStefano**

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by GregorioDiStefano** [comment]
trigger build

**Comment by kacf** [comment]
@GregorioDiStefano: Can you write a test message to @kacf from this thread? I just wanna see if I can still see user directed messages even if I'm ignoring the rest of the thread.

**Comment by GregorioDiStefano** [comment]
@kacf Good morning

**Pull request merged**
