### PR TITLE
Automatically add the '-s' command line argument to pytest

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
pytest must be called with the '-s' argument or else it will not function correctly.

I've added a pytest.ini file that automatically adds the argument on execution.

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
@kacf Another simple change to merge

**Comment by kacf** [comment]
Nice! Can you also change the `README.md` file in the same folder to remove the `-s`?

**Comment by GregorioDiStefano** [comment]
Done

**Comment by kacf** [comment]
Thanks!

**Pull request merged**
