### PR TITLE
Add io.mender.UpdateManager to D-Bus specification files.

### PR DESCRIPTION
**Pull request by kacf**
Changelog: Title

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Review by oleorhagen — APPROVED** [review]
Thanks!

**Review by lluiscampos — APPROVED** [review]
I thought we had this in place already.

**Comment by lluiscampos** [comment]
wrt to the title, I think that in D-Bus this is an "specification" file but a "policy" file.

**Comment by kacf** [comment]
This already passed in https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/310580683.

**Comment by kacf** [comment]
> wrt to the title, I think that in D-Bus this is an "specification" file but a "policy" file.

Thanks, fixed that!

**Pull request merged**
