### PR TITLE
Toradex updates for sumo

### PR DESCRIPTION
**Pull request by drewmoseley**

### CODE REVIEW

**Comment by lluiscampos** [comment]
Running tests for 2.0.1 on Jenkins: https://mender-jenkins.mender.io/job/mender-builder/4428/

**Comment by lluiscampos** [comment]
The integration test failure seems unrelated. All yocto tests passed

**Comment by drewmoseley** [comment]
@lluiscampos can this be merged?

**Comment by lluiscampos** [comment]
@drewmoseley Yes.

Merging.

**Pull request merged**
