### PR TITLE
mender: Include 2.2.1 and later versions in rocko

### PR DESCRIPTION
**Pull request by drewmoseley**
Not enabled by default.

Changelog: Title
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits have a [`Changelog`](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Add Mender 2.2.1 into Rocko.

### CODE REVIEW

**Comment by drewmoseley** [comment]
@lluiscampos @kacf these versions build unmodified in rocko and are needed for a customer project.  Any newer versions will require a core golang update which I want to avoid if possible.

**Comment by drewmoseley** [comment]
@lluiscampos can you help with the LIC_FILES_CHECKSUM fixes?

**Comment by lluiscampos** [comment]
Quite a few challenges to build for rocko nowadays. Trying Mender 2.3.1 at [Jenkins 4474](https://mender-jenkins.mender.io/job/mender-builder/4474/).

**Comment by lluiscampos** [comment]
> Quite a few challenges to build for rocko nowadays. Trying Mender 2.3.1 at [Jenkins 4474](https://mender-jenkins.mender.io/job/mender-builder/4474/).

I added few fixes and got the build started but unfortunately I got to a point where I need help from others. I'll continue on this on Monday.

**Comment by lluiscampos** [comment]
@drewmoseley For `mender` 2.2.1 (Mender product 2.3.1), the corresponding `mender-artifact` is 3.3.1. You should use #1078  instead.

**Pull request closed without merging**
