### PR TITLE
MEN-7345: Remove integration and test for systemd watchdog

### PR DESCRIPTION
**Pull request by lluiscampos**
The feature has been removed from the client (and not released in any version)

This commit in effect reverts c5bd32fe and c48b0238.

Cancel-changelog: c5bd32fe261c9b162301f779d721c1c8cdc9d055

### CODE REVIEW

**Comment by lluiscampos** [comment]
Goes with:
* https://github.com/mendersoftware/mender/pull/1668

**Comment by danielskinstad** [comment]
These variables should probably also be removed  [recipe](https://github.com/mendersoftware/meta-mender/blob/650e991751c8738121950f97cecf83f1e9077cd3/meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc#L18) and [mender-vars](https://github.com/mendersoftware/meta-mender/blob/650e991751c8738121950f97cecf83f1e9077cd3/meta-mender-core/conf/mender-vars.json#L176C1-L176C31)

**Comment by lluiscampos** [comment]
> These variables should probably also be removed [recipe](https://github.com/mendersoftware/meta-mender/blob/650e991751c8738121950f97cecf83f1e9077cd3/meta-mender-core/recipes-mender/mender-client/mender-client-cpp.inc#L18) and [mender-vars](https://github.com/mendersoftware/meta-mender/blob/650e991751c8738121950f97cecf83f1e9077cd3/meta-mender-core/conf/mender-vars.json#L176C1-L176C31)

Oh, yes! Thank you

**Review by danielskinstad — APPROVED** [review]

**Comment by lluiscampos** [comment]
New build @ [Pipeline 1478210989](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/1478210989)

**Comment by lluiscampos** [comment]
@mender-test-bot cherry-pick to:
* scarthgap

**Pull request merged**
