### PR TITLE
Test: No sensitive data leaked on D-Bus

### PR DESCRIPTION
**Pull request by oleorhagen**

### CODE REVIEW

**Comment by oleorhagen** [comment]
I'm not sure if this is as simple as this, or if I'm way off in the fields

**Review by kacf — APPROVED** [review]
That's exactly it! :smile:

**Comment by oleorhagen** [comment]
I'll wait for https://github.com/mendersoftware/meta-mender/pull/1200 before running the pipe

**Review by tranchitella — APPROVED** [review]

**Comment by tranchitella** [comment]
Manual pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/226118389

**Comment by oleorhagen** [comment]
Manual pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/226251602

**Comment by oleorhagen** [comment]
Closed, as no longer needed by the implementation!

**Pull request closed without merging**
