### PR TITLE
A few minor changes for master.

### PR DESCRIPTION
**Pull request by drewmoseley**

### CODE REVIEW

**Comment by drewmoseley** [comment]
I think @mirzak should review as well, especially for the RPI specifics.

Note that this also is needed against pyro and I'll resubmit there once it has been reviewed here.

This also contains the contents from #338 so if that one is reviewed first this will be simplified to just the one commit.

**Comment by drewmoseley** [comment]
Let's hold off on merging.  I've got one more minor commit coming that adapts the RPi UBoot patch to apply cleanly against the current master sources.

**Comment by drewmoseley** [comment]
OK.  Patch adjustment patch submitted.  As far as I can tell this is ready for merge.  I think we are still seeing CI failures but as I recall those are for issues unrelated to this specific merge request.

**Comment by GregorioDiStefano** [comment]
@drewmoseley you forgot to signoff

**Comment by drewmoseley** [comment]
@GregorioDiStefano thanks for the reminder.  These commits have been updated with Changelog entries.

**Pull request merged**
