### PR TITLE
add support for Raspberry Pi 4

### PR DESCRIPTION
**Pull request by mirzak**
Changelog: Title

Signed-off-by: Mirza Krak <mirza.krak@northern.tech>

### CODE REVIEW

**Comment by mirzak** [comment]
Should go in after, https://github.com/mendersoftware/meta-mender/pull/828

**Comment by kacf** [comment]
Nice!

For purposes of releasing, do you know if the RPi3 images run on RPi4?

**Comment by mirzak** [comment]
> For purposes of releasing, do you know if the RPi3 images run on RPi4?

Unfortunately not. Because of U-boot.

**Comment by kacf** [comment]
Ok, good to know. I suppose at some point we should start building release images for Rpi4. But I think it's not that urgent yet.

**Pull request merged**
