### PR TITLE
2.3.1 and 2.4.1 client recipes

### PR DESCRIPTION
**Pull request by oleorhagen**
If this is green and good to go, this should be cherry picked at least to:

* `Dunfell`
* `Warrior`
* `Zeus`

Any more?

### CODE REVIEW

**Comment by oleorhagen** [comment]
Or any less?

**Comment by lluiscampos** [comment]
> Or any less?

Do only `dunfell`. I'll bring it to the rest together with other fixes later this week.

**Comment by lluiscampos** [comment]
With regards to the changelog, I think we should be more explicit about the removals. I would expect something like:

* Remove recipe mender-client 2.3.0
* Add recipe mender-client 2.3.1
* Remove recipe mender-client 2.4.0
* Add recipe mender-client 2.4.1

What do you think @kacf ?

**Comment by oleorhagen** [comment]
Phew! They build ^-^

**Comment by oleorhagen** [comment]
Dunfell cherry: https://github.com/mendersoftware/meta-mender/pull/1169

**Review by kacf — APPROVED** [review]
Assuming you will adjust the changelog, and pre-approving.

**Pull request merged**
