### PR TITLE
mender: Adjust patches for U-Boot v2017.09

### PR DESCRIPTION
**Pull request by drewmoseley**
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by drewmoseley** [comment]
@kacf these updates may help in your master branch wrangling later this month.  I have not run-time tested these updates but I have verified that they build.

**Comment by drewmoseley** [comment]
Hmm.  I'm not sure why the patch failure occurred during the qemu_build here. I did a fresh checkout of sources applied my updates and the patch phase succeeded.  Are we locking down the commit hashes in the Jenkins build?

**Comment by kacf** [comment]
Yes, we are. Sorry, I didn't get around to this one yet. I am in the process of getting up to date with poky/master, which means I will probably cherry-pick this too, but the release is taking some time. Our stable hashes are in https://github.com/mendersoftware/poky, if you want to look at them.

**Comment by drewmoseley** [comment]
No worries. It makes sense to lock them down for Jenkins builds. I'm just glad my updates weren't incorrect.  They are here when you get back to re-syncing with poky/master.

**Comment by kacf** [comment]
Superseded by #387.

**Pull request closed without merging**
