### PR TITLE
Update sumo with warrior v2020.02.2

### PR DESCRIPTION
**Pull request by lluiscampos**
See thud update in #932

This PR brings to sumo a subset of #932, discarding the N.A. for this branch.

### CODE REVIEW

**Comment by lluiscampos** [comment]
Testing with Mender 2.2.1 @ [Jenkins 4464](https://mender-jenkins.mender.io/job/mender-builder/4464/)

**Comment by lluiscampos** [comment]
> Testing with Mender 2.2.1 @ [Jenkins 4464](https://mender-jenkins.mender.io/job/mender-builder/4464/)

Retrying integ tests in [Jenkins 4470](https://mender-jenkins.mender.io/job/mender-builder/4470/)

**Comment by lluiscampos** [comment]
@kacf Re-running the integration tests is becoming challenging. The latest attempts are failing on in the init script with the following error:
```
Mar 05 10:23:11 mender-jenkins-gce-ctbgf9 rc.local[1461]: W: The repository 'http://apt.dockerproject.org/repo debian-jessie Release' does not have a Release file.
Mar 05 10:23:11 mender-jenkins-gce-ctbgf9 rc.local[1461]: E: Failed to fetch http://apt.dockerproject.org/repo/dists/debian-jessie/main/binary-amd64/Packages  404  Not Found
Mar 05 10:23:11 mender-jenkins-gce-ctbgf9 rc.local[1461]: E: Some index files failed to download. They have been ignored, or old ones used instead.
```
The first run (ref [here](https://mender-jenkins.mender.io/job/mender-builder/4464/label=googlecloud%20&&%20mender_qemux86_64_uefi_grub%20&&%20mender_servers/)) failed during setup for test `test_update_failover_server`; very likely to be a framework hick-up.

What do you think about merging this PR? I will look into Jenkins setting later (whenever doing the 2.3.0 release port to thud/sumo).

**Comment by kacf** [comment]
Makes sense to me!

**Pull request merged**
