### PR TITLE
Qa 384 cherry

### PR DESCRIPTION
**Pull request by oleorhagen**

### CODE REVIEW

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Review by kacf — APPROVED** [review]
Pre-approving, but don't forget to cherry-pick https://github.com/mendersoftware/meta-mender/pull/1703/commits/85d30669d0b4304186c9e6b4934c4e39ffa09be5 (or its squashed equivalent, if you do that).

**Comment by kacf** [comment]
Oh never mind, I think I got confused by browser tabs. That commit doesn't exist here, so there's nothing to remove.

**Pull request merged**
