### PR TITLE
increase broken image from 8mb to 32mb of zeros

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>
Changelog: none

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
@kacf

**Comment by kacf** [comment]
I'd include in the commit message why you're doing this, for future reference. This is quite unintuitive. :-)

**Comment by GregorioDiStefano** [comment]
updated

**Comment by kacf** [comment]
Your tests will fail, you omitted both the changelog and the signoff. :-)

**Pull request merged**
