### PR TITLE
Zeus update v2020-09

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
Build for Mender 2.5.0 @ [Pipeline 195868742](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/195868742)

**Comment by drewmoseley** [comment]
The zeus branch of meta-oe does not have softhsm so we may need to add that recipe to our layer for the zeus branch.

**Comment by lluiscampos** [comment]
> The zeus branch of meta-oe does not have softhsm so we may need to add that recipe to our layer for the zeus branch.

I think we can skip the test instead.

**Comment by lluiscampos** [comment]
> Build for Mender 2.5.0 @ [Pipeline 195868742](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/195868742)

Testing together with https://github.com/mendersoftware/integration/pull/1026 @ [Pipeline 196059079](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/196059079)

**Comment by lluiscampos** [comment]
> > Build for Mender 2.5.0 @ [Pipeline 195868742](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/195868742)
> 
> Testing together with [mendersoftware/integration#1026](https://github.com/mendersoftware/integration/pull/1026) @ [Pipeline 196059079](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/196059079)

Repeating only integration tests with https://github.com/mendersoftware/integration/pull/1027 @ [Pipeline 196222757](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/196222757)

**Comment by lluiscampos** [comment]
Last build @ [Pipeline 196841232](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/196841232)

**Review by kacf — APPROVED** [review]

**Pull request merged**
