### PR TITLE
MEN-4808: tests and example adjust for mender CLI commands deprecation

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
Includes https://github.com/mendersoftware/mender-image-tests/pull/52

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline :thinking:

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline :police_officer:

**Review by oleorhagen — APPROVED** [review]

**Pull request merged**
