### PR TITLE
chmod 600 on mender.conf

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by estenberg** [comment]
Looks good from my knowledge, but perhaps we need to make some changes for other OSes as well (e.g. mender-convert, .deb package)?

**Comment by merlin-northern** [comment]
> Looks good from my knowledge, but perhaps we need to make some changes for other OSes as well (e.g. mender-convert, .deb package)?

yeah, this is next. I will create a ticket.

**Comment by alfrunes** [comment]
@merlin-northern would you mind changing this for mendersoftware/mender also? I believe the `mender setup` command creates mender.conf with read-all permissions.

**Comment by merlin-northern** [comment]
> > Looks good from my knowledge, but perhaps we need to make some changes for other OSes as well (e.g. mender-convert, .deb package)?
> 
> yeah, this is next. I will create a ticket.

https://tracker.mender.io/browse/MEN-3762

**Comment by merlin-northern** [comment]
> @merlin-northern would you mind changing this for mendersoftware/mender also? I believe the `mender setup` command creates mender.conf with read-all permissions.

thanks a lot! https://github.com/mendersoftware/mender/pull/566

**Comment by merlin-northern** [comment]
> Change looks good, but please add a changelog! This is a user facing change.

thanks Kristian [done](https://github.com/mendersoftware/meta-mender/pull/1023/commits/afc8ae791d016bd3398343ed2ab085137a8e5605)

**Comment by merlin-northern** [comment]
> Looks good from my knowledge, but perhaps we need to make some changes for other OSes as well (e.g. mender-convert, .deb package)?

luckly the deb package calls mender setup, and thanks fo @alfrunes 
 comment this one should do the trick: https://github.com/mendersoftware/mender/pull/566

**Comment by merlin-northern** [comment]
> Looks good from my knowledge, but perhaps we need to make some changes for other OSes as well (e.g. mender-convert, .deb package)?

and for the mender-convert https://github.com/mendersoftware/mender-convert/pull/219

**Comment by lluiscampos** [comment]
> > Looks good from my knowledge, but perhaps we need to make some changes for other OSes as well (e.g. mender-convert, .deb package)?
> 
> luckly the deb package calls mender setup, and thanks fo @alfrunes
> comment this one should do the trick: [mendersoftware/mender#566](https://github.com/mendersoftware/mender/pull/566)

Note to self; I have to review this for the official Debian package also: `mender setup` is not used there.

**Comment by merlin-northern** [comment]
@kacf all the pipelines passed:
https://gitlab.com/Northern.tech/Mender/meta-mender/-/pipelines/162775957
https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/163513632
but not reported here, can I force merge?

**Comment by kacf** [comment]
@lluiscampos: This PR did not update `pr_1023` on Gitlab, which is why the ci/gitlab pipeline did not run. It may have been exactly at the wrong moment while you were restarting hooks, but I thought you should know.

@merlin-northern: It's possible to force run this by updating Gitlab manually, but I want to let Lluis answer first in case he needs to do some forensics to fix the test-runner hook.

**Comment by lluiscampos** [comment]
> @lluiscampos: This PR did not update `pr_1023` on Gitlab, which is why the ci/gitlab pipeline did not run. It may have been exactly at the wrong moment while you were restarting hooks, but I thought you should know.
> 
> @merlin-northern: It's possible to force run this by updating Gitlab manually, but I want to let Lluis answer first in case he needs to do some forensics to fix the test-runner hook.

Thanks @kacf for reporting; I force-pushed it. We had a problem yesterday so that for couple of hours we were not updating these branches in GitLab. I found the problem and will fix and retry later today.

**Comment by merlin-northern** [comment]
thanks @lluiscampos ! and thanks @kacf !

**Comment by lluiscampos** [comment]
> > > Looks good from my knowledge, but perhaps we need to make some changes for other OSes as well (e.g. mender-convert, .deb package)?
> > 
> > 
> > luckly the deb package calls mender setup, and thanks fo @alfrunes
> > comment this one should do the trick: [mendersoftware/mender#566](https://github.com/mendersoftware/mender/pull/566)
> 
> Note to self; I have to review this for the official Debian package also: `mender setup` is not used there.

FYI, the official Debian package does not install a config file in `/etc/mender`, it does however install example files in `/usr/share/doc/mender-client/examples/`. Therefore is up to the system administrator how to configure it: using `mender setup` (which will end up with permissions 600 after these PRs) or manually and secure it as desired.

It has been very simple to test ;) On my machine:
```
sudo apt install mender-client
dpkg-query -L mender-client
```

**Pull request merged**
