### PR TITLE
mender-setup: allow setting fstab options for the boot partition 

### PR DESCRIPTION
**Pull request by kkoopa**

### CODE REVIEW

**Comment by oleorhagen** [comment]
Hi @kkoopa, before starting the review, there are a few formalities missing from the PR. We need

1) A Changelog entry
2) A signoff on your contribution, due to legalities

Also, welcome :)

Also, nice github.io page ;)

**Comment by kkoopa** [comment]
Sorry, the changelog entry and signoff are in the commit message. Is that not sufficient?

**Comment by oleorhagen** [comment]
> Sorry, the changelog entry and signoff are in the commit message. Is that not sufficient?

Yes, it is. Sry, I just noticed. I always fall for that one -_-

**Comment by oleorhagen** [comment]
@kkoopa The tests are failing, but this is not related to your PR (Most likely), as the CI has been acting up a little bit lately. Some fixes will hopefullly be merged today, and then it should turn green. 

Thank you for your patience.

**Comment by oleorhagen** [comment]
@kkoopa could you rebase on top of master so that our new acceptance tests are run?

**Comment by oleorhagen** [comment]
@kkoopa Thank you for your contribution :)

**Pull request merged**
