### PR TITLE
mender: Enable systemd in mender-systemd FEATURE handling.

### PR DESCRIPTION
**Pull request by drewmoseley**
Changelog: Title
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
That depends. Is the intention to enable the systemd bits whenever our `mender-systemd` feature is set? I'd very much like it, but I don't think this will work correctly, unfortunately. The thing is that the `classes/mender-setup-systemd.inc` file is included unconditionally, so this will always run. I don't think we can make it dependent on our `mender-systemd` feature, because that is itself a `DISTRO_FEATURE`, so using it to decide would be a circular dependency. Is that what you meant?

**Comment by mirzak** [comment]
Me and @drewmoseley, discussed this a bit and yeah the latter mentioned functionality is the desired one.

**Comment by drewmoseley** [comment]
If I make the variable settings here conditional on mender-systemd would that work?

**Comment by drewmoseley** [comment]
I added https://github.com/mendersoftware/meta-mender/pull/603/commits/f0dc1c7e76dcf69203286efc4345268d8f1abdab which is similar to how I do it in my local layer.  Does that make it any more acceptable?

**Comment by kacf** [comment]
That's the problem: There is no `MENDER_FEATURES` variable. We're just reusing `DISTRO_FEATURES` with `MENDER_FEATURES_ENABLE/DISABLE` as syntactic sugar because `DISTRO_FEATURES_BACKFILL_CONSIDERED` is such a horrible and unintuitive name for a variable. So all the features are simply listed in `DISTRO_FEATURES`, which I think means that you cannot test for the presence of something in `DISTRO_FEATURES` and also use that to modify `DISTRO_FEATURES`. Last time I tried that I got infinite recursion.

But who knows, maybe they have improved on this and they "converge" toward the stable variable assignment using multiple passes. You can try replacing `${@bb.utils.contains('MENDER_FEATURES', ...` with `${@bb.utils.contains('DISTRO_FEATURES', ...` in your commit and see if the build still works. If so, maybe we can use this.

**Comment by drewmoseley** [comment]
@kacf locally this seems to work for me.  Making it conditional on mender-systemd being in MENDER_FEATURES_ENABLE seems to do the right thing.

**Comment by drewmoseley** [comment]
Sounds good.  Closing in deference to https://github.com/mendersoftware/meta-mender/pull/608

**Pull request closed without merging**
