### PR TITLE
meta-mender-selftest: oe-selftest support

### PR DESCRIPTION
**Pull request by bboozzoo**
See README for details. Basically you can implement the same things as are implemented for OE core right here: https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/lib/oeqa/selftest

Perhaps instead of using a separate selftest layer is a bit of an overkill. The tests could be part of meta-mender-core after all. We can revise it later though, if we decide this PR is something that we want do or not.

@kacf @pasinskim @GregorioDiStefano

### CODE REVIEW

**Comment by kacf** [comment]
It would be nice to use the OE official way, but I think we should avoid the situation of having two test implementations. If we did this at all I think we would need to convert our existing test cases.

Do you know if there is any particular advantage to oe-selftest over pytest and fabric, other than aligning the workflow with OE?

**Comment by bboozzoo** [comment]
I guess it depends on a test case. For instance, if you want to verify that recipes are correct, image gets built, it has a particular layout, certain files are at specific locations, all this is doable in selftest. Also, there's no special 3rd party libraries needed, everything is already there. You could also run basic qemu based tests, wic tests do that already.

Running backend services not so much, this I'd leave to integration tests.

**Comment by kacf** [comment]
Yes, what I worry about the most is the interaction with the clients, we are using the SSH connection extensively both for QEMU and Beaglebone. I'm sure it's all possible in oe-selftest, but I expect some work will be involved to achieve it.

**Comment by bboozzoo** [comment]
Some work yes, but maybe not that much, for instance this is how wic tests do it:

```
    def test_qemu(self):
        """Test wic-image-minimal under qemu"""
        self.assertEqual(0, bitbake('wic-image-minimal').status)

        with runqemu('wic-image-minimal', ssh=False) as qemu:
            cmd = "mount |grep '^/dev/' | cut -f1,3 -d ' '"
            status, output = qemu.run_serial(cmd)
            self.assertEqual(1, status, 'Failed to run command "%s": %s' % (cmd, output))
            self.assertEqual(output, '/dev/root /\r\n/dev/vda3 /mnt')
```

There are also qemu wrappers and SSH wrappers in oeqa.

I suppose the ultimate goal is to make sure that image gets built correctly and contains everything we expect it to have without running integration tests.

**Pull request closed without merging**
