### PR TITLE
A couple of minor cleanups for master

### PR DESCRIPTION
**Pull request by drewmoseley**

### CODE REVIEW

**Comment by drewmoseley** [comment]
Changelogs added.  One of these days I'm going to remember that on the first try.

**Comment by kacf** [comment]
Sorry Drew, some problems in Jenkins. I will make sure this gets in.

**Comment by kacf** [comment]
Hey @drewmoseley, can you rebase the pull request? I think the latest meta-mender should have fixed the issues.

**Comment by drewmoseley** [comment]
Rebase complete.

**Pull request merged**
