### PR TITLE
Add recipes for Mender 2.3.1 components to sumo

### PR DESCRIPTION
**Pull request by lluiscampos**
Changelog: Add mender 2.2.1 recipe
Changelog: Add mender-artifact 3.3.1 recipe
Changelog: Remove mender 2.2.0b1 recipe
Changelog: Remove mender-artifact 3.3.0b1 recipe

### CODE REVIEW

**Comment by lluiscampos** [comment]
@drewmoseley Just for aligning these branches, I am bringing the same Mender release to sumo.

**Comment by lluiscampos** [comment]
Running tests @ [Jenkins 4485](https://mender-jenkins.mender.io/job/mender-builder/4485/)

**Review by drewmoseley — APPROVED** [review]
LGTM

**Comment by lluiscampos** [comment]
> Running tests @ [Jenkins 4485](https://mender-jenkins.mender.io/job/mender-builder/4485/)

Similar results than for #1031 but with `raspberrypi3` build passing.

**Pull request merged**
