### PR TITLE
Miscellaneous dunfell updates before release

### PR DESCRIPTION
**Pull request by lluiscampos**
Bringing #1398, #1327, #1403, #1407 and few other minor fixes.

### CODE REVIEW

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline

**Comment by lluiscampos** [comment]
Testing with `poky/dunfell-next` @ [Pipeline 328892566](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/328892566)

**Comment by lluiscampos** [comment]
Testing with `poky/dunfell-next` @ [Pipeline 328931449](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/328931449)

**Comment by lluiscampos** [comment]
Testing with `poky/dunfell-next` @ [Pipeline 328960452](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/328960452)

**Comment by lluiscampos** [comment]
New build @ [Pipeline 329465895](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/329465895)

**Review by oleorhagen — APPROVED** [review]

**Pull request merged**
