### PR TITLE
[zeus] 2.3.1 and 2.4.1 client recipes + december update

### PR DESCRIPTION
**Pull request by lluiscampos**
Porting #1168 and #1189 (except https://github.com/mendersoftware/meta-mender/pull/1189/commits/483c6b6bc6c1dc4520ce6029a99e6631500be9a0) to `zeus`.

### CODE REVIEW

**Comment by lluiscampos** [comment]
Testing with `release_tool -b 2.5.0 --pr mender/2.4.1 --pr integration/2.5.x --pr meta-mender/1172` @ [Pipeline 213580291](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/213580291).

**Comment by lluiscampos** [comment]
> Testing with `release_tool -b 2.5.0 --pr mender/2.4.1 --pr integration/2.5.x --pr meta-mender/1172` @ [Pipeline 213580291](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/213580291).

New run after https://github.com/mendersoftware/mender-qa/pull/442 @ [Pipeline 213702802](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/213702802)

**Review by kacf — APPROVED** [review]

**Comment by lluiscampos** [comment]
@kacf @oleorhagen Interestingly, `test_uboot_mender_saveenv_canary` failed for vexpress u-boot build. See full report [here](https://northern.tech.gitlab.io/-/Mender/mender-qa/-/jobs/838480551/artifacts/report_accep_vexpress_qemu.html).

**Comment by oleorhagen** [comment]
> @kacf @oleorhagen Interestingly, `test_uboot_mender_saveenv_canary` failed for vexpress u-boot build. See full report [here](https://northern.tech.gitlab.io/-/Mender/mender-qa/-/jobs/838480551/artifacts/report_accep_vexpress_qemu.html).

We had issues with these tests on the newer branches too.

> @kacf @oleorhagen Interestingly, `test_uboot_mender_saveenv_canary` failed for vexpress u-boot build. See full report [here](https://northern.tech.gitlab.io/-/Mender/mender-qa/-/jobs/838480551/artifacts/report_accep_vexpress_qemu.html).

Did we use `libubootenv` in zeus?

**Comment by lluiscampos** [comment]
> > @kacf @oleorhagen Interestingly, `test_uboot_mender_saveenv_canary` failed for vexpress u-boot build. See full report [here](https://northern.tech.gitlab.io/-/Mender/mender-qa/-/jobs/838480551/artifacts/report_accep_vexpress_qemu.html).
> 
> Did we use `libubootenv` in zeus?

I don't think so. But @kacf should be our source of truth in this issue :)

**Comment by kacf** [comment]
> Did we use `libubootenv` in zeus?

No, but it doesn't matter. Our new client check for detecting U-Boot tools requires writing to the environment at least once, and this means the test won't work anymore. @lluiscampos, the test should be removed, there should already be a change for this in master and dunfell. Ole and I discussed the implications, and although the scenario is still relevant, it is much harder to test this with the new client functionality, and ultimately we are just testing what U-Boot should already be testing themselves. It has outlived its importance, I think.

**Comment by lluiscampos** [comment]
> > Did we use `libubootenv` in zeus?
> 
> No, but it doesn't matter. Our new client check for detecting U-Boot tools requires writing to the environment at least once, and this means the test won't work anymore. @lluiscampos, the test should be removed, there should already be a change for this in master and dunfell. Ole and I discussed the implications, and although the scenario is still relevant, it is much harder to test this with the new client functionality, and ultimately we are just testing what U-Boot should already be testing themselves. It has outlived its importance, I think.

@kacf Okey, but there is something that doesn't adapt here.

The test that we removed was `test_redundant_uboot_env` (see https://github.com/mendersoftware/meta-mender/commit/6c137a727d02bcf4a04138149858e6c6da197792, which I somehow ported to `zeus` and `warrior` via submodule) while the test that is failing in this PR is `test_uboot_mender_saveenv_canary`, which passes for `warrior` for the same mender client (?).

I think I am missing something, I'll review once more the state of all branches and tests.

**Comment by kacf** [comment]
Darn, you're right, I was referring to the wrong test. The "zero test" inside `test_uboot_mender_saveenv_canary` will not pass with u-boot-fw-utils. But why did this pass on zeus before? It should have been failing for quite a long time. And I also don't see why it succeeds on warrior, which should have the same problem.

I can see three choices:

* Exclude this test by setting minimum branch version = dunfell.
* Revert submodule to before that change was introduced.
* Make a conditional inside the test itself which skips the zeroing of the environment if this is zeus or older.

**Comment by lluiscampos** [comment]
Ported #1189 except for https://github.com/mendersoftware/meta-mender/pull/1189/commits/483c6b6bc6c1dc4520ce6029a99e6631500be9a0, to be followed-up independently.

New build @ [Pipeline 226773649](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/226773649), started with:
```
release_tool -b 2.5.0 \
  --pr mender/2.4.1 \
  --pr integration/2.5.x \
  --pr meta-mender/1172
```
Indirectly includes https://github.com/mendersoftware/mender-image-tests/pull/30

> [...] but there is something that doesn't adapt here.

Mystery solved:
* In `warrior` the test is not updated, so it still expects `fw_printenv` to work (using default environment) and report no update
* In `zeus` the test was updated, and the PR that updated it failed on this test. See [PR 1153](https://github.com/mendersoftware/meta-mender/pull/1153) and [build log](https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/812140495). Different jobs in the pipeline failed for a different reason, so I overlooked specifically this test on this configuration.


> I can see three choices:
>     * Exclude this test by setting minimum branch version = dunfell.

I went for this option, see https://github.com/mendersoftware/mender-image-tests/pull/30 (indirectly included in this PR)

**Comment by lluiscampos** [comment]
Ported #1189 except for https://github.com/mendersoftware/meta-mender/pull/1189/commits/483c6b6bc6c1dc4520ce6029a99e6631500be9a0, to be followed-up independently.

New build @ [Pipeline 226773649](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/226773649), started with:
```
release_tool -b 2.5.0 \
  --pr mender/2.4.1 \
  --pr integration/2.5.x \
  --pr meta-mender/1172
```
Indirectly includes https://github.com/mendersoftware/mender-image-tests/pull/30

> [...] but there is something that doesn't adapt here.

Mystery solved:
* In `warrior` the test is not updated, so it still expects `fw_printenv` to work (using default environment) and report no update
* In `zeus` the test was updated, and the PR that updated it failed on this test. See [PR 1153](https://github.com/mendersoftware/meta-mender/pull/1153) and [build log](https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/812140495). Different jobs in the pipeline failed for a different reason, so I overlooked specifically this test on this configuration.


> I can see three choices:
>     * Exclude this test by setting minimum branch version = dunfell.

I went for this option, see https://github.com/mendersoftware/mender-image-tests/pull/30 (indirectly included in this PR)

> Ported #1189 except for [483c6b6](https://github.com/mendersoftware/meta-mender/commit/483c6b6bc6c1dc4520ce6029a99e6631500be9a0), to be followed-up independently.
> 
> New build @ [Pipeline 226773649](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/226773649), started with:
> 
> ```
> release_tool -b 2.5.0 \
>   --pr mender/2.4.1 \
>   --pr integration/2.5.x \
>   --pr meta-mender/1172
> ```
> 

Fixed an small issue with a test. New build @ [Pipeline 226978775](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/226978775)

**Review by kacf — APPROVED** [review]

**Pull request merged**
