### PR TITLE
MEN-4712: monitor-client yocto integration (internal flow)

### PR DESCRIPTION
**Pull request by lluiscampos**
* MEN-4712: meta-mender-commercial: Add monitor-client git recipe
* MEN-4712: Add new image monitor-image-full-cmdline for internal testing

`Changelog: Title` in both

### CODE REVIEW

**Comment by lluiscampos** [comment]
All these PRs go together:
* https://github.com/mendersoftware/mender-qa/pull/509
* https://github.com/mendersoftware/integration/pull/1417
* https://github.com/mendersoftware/meta-mender/pull/1396
* https://github.com/mendersoftware/monitor-client/pull/9

Being tested @ [Pipeline 320560866](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/320560866).

**Comment by lluiscampos** [comment]
Ready for review!

Last build @ [Pipeline 321015108](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/321015108)

**Comment by lluiscampos** [comment]
Repeating pipeline for client acceptance tests, see https://github.com/mendersoftware/mender-qa/pull/509#issuecomment-861442850

**Comment by lluiscampos** [comment]
All updated for the `monitor-client`-> `mender-monitor` rename:
* https://github.com/mendersoftware/mender-qa/pull/509
* https://github.com/mendersoftware/integration/pull/1417
* https://github.com/mendersoftware/meta-mender/pull/1396
* https://github.com/mendersoftware/monitor-client/pull/12 (new)

Being tested @ [Pipeline 322643421](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/322643421).

**Review by kacf — APPROVED** [review]

**Pull request merged**
