### PR TITLE
use temporary directory for extracting images in mender-qemu 

### PR DESCRIPTION
**Pull request by bboozzoo**
@kacf @drewmoseley @GregorioDiStefano

### CODE REVIEW

**Comment by drewmoseley** [comment]
Looks good to me.  Thanks.

**Comment by bboozzoo** [comment]
Raw flash tests were not being run for some time. Now that they're running again, `TestBuild::test_tenant_token` was failing. Fixed this in last commit.

**Comment by bboozzoo** [comment]
we should merge once integration tests pass as it's blocking #367 and #368

**Comment by GregorioDiStefano** [comment]
finally, everything passed.

**Comment by bboozzoo** [comment]
merge?

**Pull request merged**
